import { StyleSheet } from 'react-native';

export const adminStyles = StyleSheet.create({
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 50,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 120,
    },
    tabScrollView: {
        borderRadius: 14,
        marginHorizontal: 20,
        marginTop: 16,
        marginBottom: 8,
        flexGrow: 0,
    },
    tabScrollContent: {
        flexDirection: 'row',
        padding: 4,
        gap: 4,
    },
    tabButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 10,
    },
    sectionContainer: {
        marginTop: 16,
    },
    sectionHeading: {
        marginBottom: 16,
        letterSpacing: 0.5,
    },
    card: {
        borderRadius: 20,
        padding: 18,
        marginBottom: 20,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    cardLabel: {
        marginBottom: 14,
        letterSpacing: 1,
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    settingInfo: {
        flex: 1,
        marginRight: 16,
    },
    quickDates: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        justifyContent: 'flex-start',
    },
    presetCard: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        paddingHorizontal: 8,
    },
    calendarMonthNav: {
        padding: 6,
        borderRadius: 10,
    },
    weekDaysRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    weekDayHeader: {
        width: `${100 / 7}%`,
        textAlign: 'center',
        fontSize: 11,
    },
    daysGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    calendarDayCell: {
        width: `${100 / 7}%`,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 20,
        marginVertical: 2,
        position: 'relative',
    },
    calendarDayCellEmpty: {
        width: `${100 / 7}%`,
        height: 40,
    },
    calendarDayCellDisabled: {
        opacity: 0.4,
    },
    todayIndicator: {
        position: 'absolute',
        bottom: 4,
        width: 4,
        height: 4,
        borderRadius: 2,
    },
    statusCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        borderRadius: 16,
        marginBottom: 24,
    },
    saveButton: {
        height: 56,
        borderRadius: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 24,
    },
    statsCard: {
        width: '48%',
        borderRadius: 20,
        padding: 16,
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        height: 125,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
    },
    statsCount: {
        fontSize: 28,
        marginTop: 10,
        marginBottom: 2,
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
    },
    statusRowLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    tourCard: {
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    tourHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    tourHeaderLeft: {
        flex: 1,
        marginRight: 10,
    },
    tourDescription: {
        marginTop: 10,
        lineHeight: 18,
    },
    tourStatsRow: {
        flexDirection: 'row',
        gap: 16,
        marginTop: 12,
        borderBottomWidth: 1,
        borderBottomColor: 'transparent',
        paddingBottom: 12,
    },
    moderationActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
        gap: 10,
    },
    moderationBtn: {
        flex: 1,
        height: 40,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyModerationCard: {
        borderRadius: 20,
        padding: 32,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#10b98140',
        marginTop: 8,
    },
    detailsToggleBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        marginTop: 8,
        borderTopWidth: 1,
    },
    detailsContainer: {
        borderRadius: 14,
        padding: 12,
        marginTop: 6,
        marginBottom: 12,
    },
    detailsSection: {
        marginBottom: 12,
    },
    detailsSectionTitle: {
        fontSize: 12,
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    detailItem: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: 'rgba(0,0,0,0.02)',
        marginBottom: 6,
    },
    stopDetailItem: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: 'rgba(0,0,0,0.02)',
        marginBottom: 8,
    },
    searchBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 12,
        borderWidth: 1,
        paddingHorizontal: 12,
        height: 46,
        marginBottom: 16,
    },
    searchBarInput: {
        flex: 1,
        fontSize: 14,
        height: '100%',
    },
    userCardHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingBottom: 12,
    },
    userStatsBox: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        backgroundColor: 'rgba(0,0,0,0.04)',
    },
    userCardActions: {
        flexDirection: 'row',
        gap: 10,
        paddingTop: 12,
        marginTop: 8,
    },
    userActionBtn: {
        flex: 1,
        height: 38,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    reviewHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 6,
    },
    ratingStars: {
        flexDirection: 'row',
        gap: 2,
    },
    editUserForm: {
        gap: 12,
    },
    inputGroup: {
        marginBottom: 8,
    },
    inputLabel: {
        fontSize: 10,
        marginBottom: 4,
        letterSpacing: 0.5,
    },
    formInput: {
        height: 40,
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        fontSize: 14,
    },
    rowInputs: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    formActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
        marginTop: 8,
    },
    formActionBtn: {
        height: 36,
        paddingHorizontal: 16,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        minWidth: 80,
    },
    sortContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    sortChipsScroll: {
        flexDirection: 'row',
        gap: 6,
        alignItems: 'center',
        paddingLeft: 4,
    },
    sortChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    notificationBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        marginHorizontal: 16,
        marginTop: 10,
        marginBottom: 2,
        borderRadius: 12,
        borderWidth: 1,
    },
});
