// src/i18n/strings.ts
export const strings = {
  en: {
    profile: 'Profile',
    manageAccount: 'Manage your account',
    personalInfo: 'Personal Information',
    appPreferences: 'App Preferences',
    contact: 'Contact',
    terms: 'Terms & Conditions',
    faq: 'Frequently Asked Questions',
    darkMode: 'Dark Mode',
    language: 'Language',
    currentAdventure: 'YOUR CURRENT ADVENTURE',
    completed: 'Completed',
    resumeTour: 'Resume Tour',
    explore: 'Explore',
    join: 'Join',
    create: 'Create',
    tour: 'Tour',
    map: 'Map',
    stops: 'Stops',
    by: 'by',
    reviews: 'reviews',
    startTour: 'Start Tour',
    overview: 'Overview',
    itinerary: 'Itinerary',
    reviewsTab: 'Reviews',
    tourMap: 'Tour Map',
    topPlayers: 'Top Players this week',
    tourWideChallenges: 'Tour Wide Challenges',
    tourStops: 'Tour Stops',
    userReviews: 'User Reviews',
    // New keys for tour components
    clickToViewRoute: 'Click to view route',
    backToAllTours: 'Back to all tours',
    createdBy: 'Created by',
    distance: 'Distance',
    duration: 'Duration',
    points: 'Points',
    pts: 'pts',
    xp: 'XP',
    aboutThisTour: 'About this tour',
    gameModes: 'Game Modes',
    challengesIncluded: 'Challenges Included',
    uniqueChallengesAcross: 'unique challenges across',
    viewOnMap: 'View on Map',
    gallery: 'Gallery',
    sortBy: 'Sort by',
    newest: 'Newest',
    oldest: 'Oldest',
    highestRating: 'Highest Rated',
    lowestRating: 'Lowest Rated',
    showMore: 'Show More',
    showLess: 'Show Less',
    popularTours: 'Popular Tours',
    // Profile card keys
    level: 'Level',
    explorer: 'Explorer',
    levelProgress: 'Level Progress',
    created: 'Created',
    completeAllChallengesToContinue: 'Complete all challenges to continue',
    Stop: 'Stop',
    nextLevel: 'Next level',
    yourTokens: 'Your Tokens',
    buyTokens: 'Buy Tokens',
    inviteFriends: 'Invite Friends',
    chooseTokenPackage: 'Choose a token package to continue playing tours',
    mostPopular: 'Most Popular',
    bonus: 'Bonus',
    total: 'Total',
    tokensLower: 'tokens',
    earnFreeTokens: 'Earn Free Tokens!',
    inviteFriendsDescription: 'Invite friends and earn 3 tokens for each friend who joins. Tap "Invite Friends" to get your referral link!',
    toursDone: 'Tours Done',
    toursCreated: 'Tours Created',
    totalPoints: 'Total Points',
    friends: 'Friends',
    recentAchievements: 'Recent Achievements',
    // Active Tour keys
    createTour: 'Create Tour',
    createTourSubtitle: 'Design your own adventure',
    stepInfo: 'Basic Info',
    stepGamemodes: 'Gamemodes',
    stepStops: 'Stops',
    stepReview: 'Review',
    tourTitle: 'Tour Title',
    tourDescription: 'Description',
    tourLocation: 'Location',
    tourImage: 'Image URL',
    difficulty: 'Difficulty',
    selectGameModes: 'Select Game Modes',
    addStop: 'Add Stop',
    editStop: 'Edit Stop',
    playForFree: 'Creator plays for FREE!',
    createAndStart: 'Create & Start',
    stopName: 'Stop Name',
    stopType: 'Stop Type',
    stopDescription: 'Stop Description',
    latitude: 'Latitude',
    longitude: 'Longitude',
    addChallenge: 'Add Challenge',
    editChallenge: 'Edit Challenge',
    challengeTitle: 'Challenge Title',
    challengeQuestion: 'Question / Task',
    challengeAnswer: 'Answer (for Trivia)',
    challengePoints: 'Points',
    nextStep: 'Next Step',
    prevStep: 'Previous',
    finalReview: 'Final Review',
    tourCreatedSuccess: 'Tour Created Successfully!',
    fillAllFields: 'Please fill in all required fields',
    loadingTour: 'Loading tour...',
    tourNotFound: 'Tour not found',
    challenges: 'Challenges',
    noChallengesAtStop: 'No challenges at this stop. Enjoy the view!',
    challengeCompleted: 'Challenge Completed!',
    challengeFailed: 'Challenge Failed',
    navigate: 'Navigate',
    wrongAnswer: 'Wrong Answer',
    claimPoints: 'Claim Points',
    submitAnswer: 'Submit Answer',
    rightLocation: "You're at the right location!",
    wrongAnswerCorrectWas: 'Wrong answer! The correct answer was:',
    back: 'Back',
    finishTour: 'Finish Tour',
    next: 'Next',
    tokens: 'Tokens',
    pubgolf: 'Pub Golf',
    info: 'Info',
    // Pub Golf specific
    par: 'Par',
    sipsTaken: 'Sips taken:',
    holeInOne: 'HOLE IN ONE!',
    legendary: 'Legendary!',
    albatross: 'Albatross!',
    unreal: 'Unreal!',
    eagle: 'EAGLE!',
    amazing: 'Amazing!',
    birdie: 'Birdie!',
    greatJob: 'Great job!',
    parScore: 'PAR!',
    perfect: 'Perfect!',
    bogey: 'Bogey!',
    niceTry: 'Nice try!',
    doubleBogey: 'Double Bogey',
    tripleBogeyPlus: 'Triple Bogey+',
    evenPar: 'Even Par',
    underPar: 'Under Par!',
    overPar: 'Over Par',
    officialScorecard: 'Official Scorecard',
    totalScore: 'Total Score',
    pubGolfInstructions: 'Try to finish each drink in par or under! Lower score wins.',
    pubGolfLegend: 'Eagle (-2) • Birdie (-1) • Par (0) • Bogey (+1)',
    drink: 'Drink',
    // Team Setup
    teamSetup: 'Team Setup',
    customizeTeam: 'Customize your team for the tour!',
    teamName: 'Team Name',
    enterTeamName: 'Enter team name...',
    teamColor: 'Team Color',
    teamEmoji: 'Team Emoji',
    preview: 'Preview',
    yourTeamName: 'Your Team Name',
    createTeam: 'Create Team',
    creating: 'Creating...',
    missingInfo: 'Missing Info',
    enterTeamNameAlert: 'Please enter a team name',
    activeTourExists: 'Active Tour Exists',
    activeTourExistsMessage: 'You have an active tour. Starting a new one will cause you to lose progress. Do you want to proceed?',
    startTourCostTitle: 'Start Tour Cost',
    startTourCostMessage: 'Starting a tour costs 1 token. You currently have {0} tokens.',
    insufficientTokensTitle: 'Insufficient Tokens',
    insufficientTokensMessage: 'You do not have enough tokens to start a tour. Please buy more.',
    proceed: 'Proceed',
    cancel: 'Cancel',
    startNew: 'Start New',
    failedToCreateTeam: 'Failed to create team. Please try again.',
    loginRequired: 'Login Required',
    loading: 'Loading...',
    pendingInvites: 'Pending Invites',
    // Join Tour keys
    joinTour: 'Join Tour',
    enterTourCode: 'Enter Tour Code',
    getItFromHost: 'Get it from your tour host',
    tourCodeLabel: 'Tour Code',
    joinTourButton: 'Join Tour',
    verifying: 'Verifying...',
    or: 'or',
    scanQrCode: 'Scan QR Code',
    tapToScan: 'Tap to open camera and scan',
    invalidTourCode: 'Invalid Tour Code',
    failedToJoin: 'Failed to join tour',
    shareThisCode: 'Share this code with your team!',
    setupTeam: 'Setup Team',
    marketingLobbyTitle: "You're in!",
    marketingLobbySubtitle: 'Wait for others to join, then setup your team.',
    saveAndStart: 'Save & Start',
    saveTeam: 'Save Team',
    editTeam: 'Edit Team',
    ready: 'Ready!',
    howItWorks: 'How it works',
    howItWorksStep1: '1. Get the tour code from your host',
    howItWorksStep2: '2. Enter the code above',
    howItWorksStep3: '3. Create or join a team',
    howItWorksStep4: '4. Start your adventure!',
    teamPlay: 'Team Play',
    teamPlayDesc: 'Join forces with friends or compete against other teams in epic challenges!',
    // New Challenge Types
    uploading: 'Uploading...',
    takePhoto: 'Take Photo',
    true: 'True',
    false: 'False',
    dareCompleted: 'I did it!',
    hideHint: 'Hide Hint',
    showHint: 'Need a hint?',
    enterAnswer: 'Enter your answer...',
    correctAnswerWas: 'Answer:',
    // Auth Keys
    login: 'Login',
    signUp: 'Sign Up',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Enter your credentials to continue your journey.',
    createAccount: 'Create Account',
    registerSubtitle: 'Join the adventure and start tracking your taps.',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    passwordsDoNotMatch: 'Passwords do not match',
    resetLinkSent: 'Reset link sent!',
    checkEmailForReset: 'Check your email for the reset link.',
    forgotPasswordSubtitle: 'Enter your email to receive a password reset link.',
    failedToLogin: 'Failed to login',
    failedToRegister: 'Failed to register',
    failedToReset: 'Failed to send reset link',
    loggingIn: 'Logging in...',
    registering: 'Registering...',
    sending: 'Sending...',
    logout: 'Logout',
    resendConfirmation: 'Resend Confirmation Email',
    emailNotConfirmed: 'Email not confirmed',
    confirmationSent: 'Confirmation email sent!',
    authenticationRequired: 'Authentication Required',
    loginToStartTour: 'You need to be logged in to start a tour.',
    signIn: 'Sign In',
    googleSignIn: 'Sign in with Google',
    pleaseLoginToManageYourPersonalDetails: 'Please login to manage your personal details.',
    mustBeLoggedIn: 'You must be logged in to perform this action.',
    // Tour Completed
    tourCompleted: 'Tour Complete! 🎉',
    writeReview: 'Write a Review',
    reviewSubmitted: 'Review Submitted!',
    reviewSubmittedTitle: 'Success',
    reviewSubmittedMessage: 'Thank you for your review!',
    backToHome: 'Back to Home',
    submitReview: 'Submit Review',
    reviewPlaceholder: 'What did you think about this tour?',
    error: 'Error',
    reviewSubmitError: 'Failed to submit review. Please try again.',
    // Waiting Lobby
    greatJobTitle: 'Great Job! 🎯',
    waitingForTeams: 'Waiting for other teams to finish...',
    tourProgress: 'Tour Progress',
    teamsCompleted: '{0} of {1} teams completed',
    finished: 'Finished!',
    inProgress: 'In progress...',
    playersCount: '{0} players',
    yourTeam: 'Your Team',
    viewResults: 'View Results',
    autoResults: 'Results will show automatically when everyone finishes',
    saveChanges: 'Save Changes',
    name: 'Name',
    profilePicture: 'Profile Picture',
    change: 'Change',
    updateSuccess: 'Profile updated successfully!',
    updateError: 'Failed to update profile.',
    viewRulesAndScoring: 'View Rules & Scoring',
    scoring: 'Scoring',
    // Create Tour Flow
    stepInfoTitle: "Let's verify the basics.",
    stepInfoSubtitle: "Give your adventure a catchy name and location.",
    titlePlaceholder: "e.g. The Hidden Gems of Paris",
    locationPlaceholder: "e.g. Paris, France",
    descPlaceholder: "What makes this tour special?",
    imagePlaceholder: "https://example.com/image.jpg",
    stepGamemodesTitle: "Choose the vibe.",
    stepGamemodesSubtitle: "Add special game modes to your tour.",
    pubGolfDescription: "A boozy adventure. Score par on drinks. Strictly 18+.",
    comingSoon: "More Coming Soon...",
    comingSoonDesc: "Bingo, Crazy 88, and more are on the way!",
    stepStopsTitle: "Map your adventure.",
    stepStopsSubtitle: "Add stops, then add challenges to them.",
    emptyStopText: "Start by adding a location",
    confirmLocation: "Confirm Location",
    addChallengeButton: "Add Challenge",
    stepReviewTitle: "Ready to launch?",
    stepReviewSubtitle: "Review your tour card. Tap the distance or time to edit details.",
    step: "Step",
    you: "You",
    new: "New",
    km: "km",
    min: "min",
  },
  es: {
    profile: 'Perfil',

    manageAccount: 'Administrar su cuenta',
    personalInfo: 'Información personal',
    appPreferences: 'Preferencias de la app',
    contact: 'Contacto',
    terms: 'Términos y condiciones',
    faq: 'Preguntas frecuentes',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    currentAdventure: 'TU AVENTURA ACTUAL',
    completed: 'Completado',
    resumeTour: 'Continuar Tour',
    explore: 'Explorar',
    join: 'Unirse',
    create: 'Crear',
    tour: 'Tour',
    map: 'Mapa',
    stops: 'Paradas',
    by: 'por',
    reviews: 'reseñas',
    startTour: 'Comenzar Tour',
    overview: 'Resumen',
    itinerary: 'Itinerario',
    reviewsTab: 'Reseñas',
    tourMap: 'Mapa del Tour',
    topPlayers: 'Mejores jugadores de la semana',
    tourWideChallenges: 'Desafíos del Tour',
    tourStops: 'Paradas del Tour',
    userReviews: 'Reseñas de usuarios',
    // New keys for tour components
    clickToViewRoute: 'Haga clic para ver la ruta',
    backToAllTours: 'Volver a todos los tours',
    createdBy: 'Creado por',
    distance: 'Distancia',
    duration: 'Duración',
    points: 'Puntos',
    pts: 'pts',
    xp: 'XP',
    aboutThisTour: 'Sobre este tour',
    gameModes: 'Modos de Juego',
    challengesIncluded: 'Desafíos Incluidos',
    uniqueChallengesAcross: 'desafíos únicos en',
    viewOnMap: 'Ver en Mapa',
    gallery: 'Galería',
    sortBy: 'Ordenar por',
    newest: 'Más reciente',
    oldest: 'Más antiguo',
    highestRating: 'Mejor valorado',
    lowestRating: 'Menor valorado',
    showMore: 'Mostrar más',
    showLess: 'Mostrar menos',
    popularTours: 'Tours Populares',
    // Profile card keys
    level: 'Nivel',
    explorer: 'Explorador',
    levelProgress: 'Progreso de Nivel',
    created: 'Creado',
    completeAllChallengesToContinue: 'Completa todos los desafíos para continuar',
    Stop: 'Parada',
    nextLevel: 'Siguiente nivel',
    yourTokens: 'Tus Fichas',
    buyTokens: 'Comprar Fichas',
    inviteFriends: 'Invitar Amigos',
    chooseTokenPackage: 'Elige un paquete de fichas para seguir jugando tours',
    mostPopular: 'Más Popular',
    bonus: 'Bono',
    total: 'Total',
    tokensLower: 'fichas',
    earnFreeTokens: '¡Gana Fichas Gratis!',
    inviteFriendsDescription: 'Invita a amigos y gana 3 fichas por cada amigo que se una. ¡Toca "Invitar Amigos" para obtener tu enlace de referencia!',
    toursDone: 'Tours Realizados',
    toursCreated: 'Tours Creados',
    totalPoints: 'Puntos Totales',
    friends: 'Amigos',
    recentAchievements: 'Logros Recientes',
    // Active Tour keys
    loadingTour: 'Cargando tour...',
    tourNotFound: 'Tour no encontrado',
    challenges: 'Desafíos',
    noChallengesAtStop: 'No hay desafíos en esta parada. ¡Disfruta la vista!',
    challengeCompleted: '¡Desafío Completado!',
    challengeFailed: 'Desafío Fallido',
    navigate: 'Navegar',
    wrongAnswer: 'Respuesta Incorrecta',
    claimPoints: 'Reclamar Puntos',
    submitAnswer: 'Enviar Respuesta',
    rightLocation: '¡Estás en la ubicación correcta!',
    wrongAnswerCorrectWas: '¡Respuesta incorrecta! La respuesta correcta era:',
    back: 'Atrás',
    finishTour: 'Terminar Tour',
    next: 'Siguiente',
    tokens: 'Fichas',
    pubgolf: 'Pub Golf',
    info: 'Info',
    // Pub Golf specific
    par: 'Par',
    sipsTaken: 'Sorbos tomados:',
    holeInOne: '¡HOYO EN UNO!',
    legendary: '¡Legendario!',
    albatross: '¡Albatros!',
    unreal: '¡Irreal!',
    eagle: '¡ÁGUILA!',
    amazing: '¡Increíble!',
    birdie: '¡Pajarito!',
    greatJob: '¡Gran trabajo!',
    parScore: '¡PAR!',
    perfect: '¡Perfecto!',
    bogey: '¡Bogey!',
    niceTry: '¡Buen intento!',
    doubleBogey: 'Doble Bogey',
    tripleBogeyPlus: 'Triple Bogey+',
    evenPar: 'Par',
    underPar: '¡Bajo Par!',
    overPar: 'Sobre Par',
    officialScorecard: 'Tarjeta de Puntuación Oficial',
    totalScore: 'Puntuación Total',
    pubGolfInstructions: '¡Intenta terminar cada bebida en par o menos! La puntuación más baja gana.',
    pubGolfLegend: 'Águila (-2) • Pajarito (-1) • Par (0) • Bogey (+1)',
    drink: 'Bebida',
    loginRequired: 'Inicio de sesión obligatorio',
    loading: 'Cargando...',
    pendingInvites: 'Invitaciones Pendientes',
    // Join Tour keys
    joinTour: 'Unirse al Tour',
    enterTourCode: 'Ingresar Código del Tour',
    getItFromHost: 'Consíguelo de tu anfitrión',
    tourCodeLabel: 'Código del Tour',
    joinTourButton: 'Unirse al Tour',
    verifying: 'Verificando...',
    or: 'o',
    scanQrCode: 'Escanear Código QR',
    tapToScan: 'Toca para abrir cámara y escanear',
    invalidTourCode: 'Código del Tour Inválido',
    startTourCostTitle: 'Costo del Tour',
    startTourCostMessage: 'Iniciar un tour cuesta 1 ficha. Actualmente tienes {0} fichas.',
    insufficientTokensTitle: 'Fichas Insuficientes',
    insufficientTokensMessage: 'No tienes suficientes fichas para iniciar un tour. Por favor compra más.',
    proceed: 'Continuar',
    cancel: 'Cancelar',
    failedToJoin: 'Error al unirse al tour',
    setupTeam: 'Configurar Equipo',
    marketingLobbyTitle: '¡Estás dentro!',
    marketingLobbySubtitle: 'Espera a que otros se unan, luego configura tu equipo.',
    saveAndStart: 'Guardar y Empezar',
    saveTeam: 'Guardar Equipo',
    editTeam: 'Editar Equipo',
    ready: '¡Listo!',
    howItWorks: 'Cómo funciona',
    howItWorksStep1: '1. Obtén el código del tour de tu anfitrión',
    howItWorksStep2: '2. Ingresa el código arriba',
    howItWorksStep3: '3. Crea o únete a un equipo',
    howItWorksStep4: '4. ¡Comienza tu aventura!',
    teamPlay: 'Juego en Equipo',
    teamPlayDesc: '¡Une fuerzas con amigos o compite contra otros equipos en desafíos épicos!',
    // New Challenge Types
    takePhoto: 'Tomar Foto',
    true: 'Verdadero',
    false: 'Falso',
    dareCompleted: '¡Lo hice!',
    hideHint: 'Ocultar Pista',
    showHint: '¿Necesitas una pista?',
    enterAnswer: 'Ingresa tu respuesta...',
    correctAnswerWas: 'Respuesta:',
    // Auth Keys
    login: 'Iniciar sesión',
    signIn: 'Ingresar',
    googleSignIn: 'Iniciar con Google',
    signUp: 'Registrarse',
    register: 'Registrar',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    resetPassword: 'Restablecer contraseña',
    noAccount: '¿No tienes una cuenta?',
    haveAccount: '¿Ya tienes una cuenta?',
    sendResetLink: 'Enviar enlace',
    backToLogin: 'Volver a iniciar sesión',
    welcomeBack: 'Bienvenido de nuevo',
    loginSubtitle: 'Ingresa tus credenciales para continuar tu viaje.',
    createAccount: 'Crear cuenta',
    registerSubtitle: 'Únete a la aventura y comienza tu seguimiento.',
    enterEmail: 'Ingresa tu correo',
    enterPassword: 'Ingresa tu contraseña',
    passwordsDoNotMatch: 'Las contraseñas no coinciden',
    resetLinkSent: '¡Enlace enviado!',
    checkEmailForReset: 'Revisa tu correo para el enlace de restablecimiento.',
    forgotPasswordSubtitle: 'Ingresa tu correo para recibir un enlace de recuperación.',
    failedToLogin: 'Error al iniciar sesión',
    failedToRegister: 'Error al registrarse',
    failedToReset: 'Error al enviar enlace',
    loggingIn: 'Iniciando sesión...',
    registering: 'Registrando...',
    sending: 'Enviando...',
    logout: 'Cerrar sesión',
    resendConfirmation: 'Reenviar correo de confirmación',
    emailNotConfirmed: 'Correo no confirmado',
    confirmationSent: '¡Correo de confirmación enviado!',
    pleaseLoginToManageYourPersonalDetails: 'Por favor, inicia sesión para gestionar tus datos personales.',
    mustBeLoggedIn: 'Debes iniciar sesión para realizar esta acción.',
    // Tour Completed
    tourCompleted: '¡Tour Completado! 🎉',
    writeReview: 'Escribir Reseña',
    reviewSubmitted: '¡Reseña Enviada!',
    reviewSubmittedTitle: 'Éxito',
    reviewSubmittedMessage: '¡Gracias por tu reseña!',
    backToHome: 'Volver al Inicio',
    submitReview: 'Enviar Reseña',
    reviewPlaceholder: '¿Qué te pareció este tour?',
    error: 'Error',
    reviewSubmitError: 'Error al enviar la reseña. Por favor inténtalo de nuevo.',
    // Waiting Lobby
    greatJobTitle: '¡Buen Trabajo! 🎯',
    waitingForTeams: 'Esperando a que otros equipos terminen...',
    tourProgress: 'Progreso del Tour',
    teamsCompleted: '{0} de {1} equipos completados',
    finished: '¡Terminado!',
    inProgress: 'En progreso...',
    playersCount: '{0} jugadores',
    yourTeam: 'Tu Equipo',
    viewResults: 'Ver Resultados',
    autoResults: 'Los resultados se mostrarán automáticamente cuando todos terminen',
    saveChanges: 'Guardar cambios',
    name: 'Nombre',
    profilePicture: 'Foto de perfil',
    change: 'Cambiar',
    updateSuccess: '¡Perfil actualizado con éxito!',
    updateError: 'Error al actualizar el perfil.',
    viewRulesAndScoring: 'Ver Reglas y Puntuación',
    scoring: 'Puntuación',
  },
  nl: {
    profile: 'Profiel',
    manageAccount: 'Beheer uw account',
    personalInfo: 'Persoonlijke informatie',
    appPreferences: 'App-voorkeuren',
    contact: 'Contact',
    terms: 'Algemene voorwaarden',
    faq: 'Veelgestelde vragen',
    darkMode: 'Donkere modus',
    language: 'Taal',
    currentAdventure: 'JE HUIDIGE AVONTUUR',
    completed: 'Voltooid',
    resumeTour: 'Tour Hervatten',
    explore: 'Verkennen',
    join: 'Meedoen',
    create: 'Maken',
    tour: 'Tour',
    map: 'Kaart',
    stops: 'Stops',
    by: 'door',
    reviews: 'beoordelingen',
    startTour: 'Start Tour',
    overview: 'Overzicht',
    itinerary: 'Reisplan',
    reviewsTab: 'Beoordelingen',
    tourMap: 'Tourkaart',
    topPlayers: 'Topspelers deze week',
    tourWideChallenges: 'Tourbrede uitdagingen',
    tourStops: 'Tourstops',
    userReviews: 'Gebruikersbeoordelingen',
    // New keys for tour components
    clickToViewRoute: 'Klik om route te bekijken',
    backToAllTours: 'Terug naar alle tours',
    createdBy: 'Gemaakt door',
    distance: 'Afstand',
    duration: 'Duur',
    points: 'Punten',
    pts: 'ptn',
    xp: 'XP',
    aboutThisTour: 'Over deze tour',
    gameModes: 'Spelmodi',
    challengesIncluded: 'Uitdagingen Inbegrepen',
    uniqueChallengesAcross: 'unieke uitdagingen over',
    viewOnMap: 'Bekijk op Kaart',
    gallery: 'Galerij',
    sortBy: 'Sorteer op',
    newest: 'Nieuwste',
    oldest: 'Oudste',
    highestRating: 'Hoogst gewaardeerd',
    lowestRating: 'Laagst gewaardeerd',
    showMore: 'Toon meer',
    showLess: 'Toon minder',
    popularTours: 'Populaire Tours',
    // Profile card keys
    level: 'Niveau',
    explorer: 'Verkenner',
    levelProgress: 'Niveauvoortgang',
    created: 'Gemaakt',
    completeAllChallengesToContinue: 'Voltooi alle uitdagingen om door te gaan',
    Stop: 'Stop',
    nextLevel: 'Volgend niveau',
    yourTokens: 'Jouw Tokens',
    buyTokens: 'Tokens Kopen',
    inviteFriends: 'Vrienden Uitnodigen',
    chooseTokenPackage: 'Kies een tokenpakket om tours te blijven spelen',
    mostPopular: 'Meest Populair',
    bonus: 'Bonus',
    total: 'Totaal',
    tokensLower: 'tokens',
    earnFreeTokens: 'Verdien Gratis Tokens!',
    inviteFriendsDescription: 'Nodig vrienden uit en verdien 3 tokens voor elke vriend die lid wordt. Tik op "Vrienden Uitnodigen" om je verwijzingslink te krijgen!',
    toursDone: 'Tours Gedaan',
    toursCreated: 'Tours Gemaakt',
    totalPoints: 'Totaal Punten',
    friends: 'Vrienden',
    recentAchievements: 'Recente Prestaties',
    // Active Tour keys
    loadingTour: 'Tour laden...',
    tourNotFound: 'Tour niet gevonden',
    challenges: 'Uitdagingen',
    noChallengesAtStop: 'Geen uitdagingen bij deze stop. Geniet van het uitzicht!',
    challengeCompleted: 'Uitdaging Voltooid!',
    challengeFailed: 'Uitdaging Mislukt',
    navigate: 'Navigeren',
    wrongAnswer: 'Verkeerd Antwoord',
    claimPoints: 'Punten Claimen',
    submitAnswer: 'Antwoord Indienen',
    rightLocation: 'Je bent op de juiste locatie!',
    wrongAnswerCorrectWas: 'Verkeerd antwoord! Het juiste antwoord was:',
    back: 'Terug',
    finishTour: 'Tour Beëindigen',
    next: 'Volgende',
    tokens: 'Tokens',
    pubgolf: 'Pub Golf',
    info: 'Info',
    // Pub Golf specific
    par: 'Par',
    sipsTaken: 'Slokken genomen:',
    holeInOne: 'HOLE IN ONE!',
    legendary: 'Legendarisch!',
    albatross: 'Albatros!',
    unreal: 'Onwerkelijk!',
    eagle: 'EAGLE!',
    amazing: 'Geweldig!',
    birdie: 'Birdie!',
    greatJob: 'Goed gedaan!',
    parScore: 'PAR!',
    perfect: 'Perfect!',
    bogey: 'Bogey!',
    niceTry: 'Goed geprobeerd!',
    doubleBogey: 'Dubbele Bogey',
    tripleBogeyPlus: 'Drievoudige Bogey+',
    evenPar: 'Even Par',
    underPar: 'Onder Par!',
    overPar: 'Boven Par',
    officialScorecard: 'Officiële Scorekaart',
    totalScore: 'Totale Score',
    pubGolfInstructions: 'Probeer elk drankje in par of minder te eindigen! Lagere score wint.',
    pubGolfLegend: 'Eagle (-2) • Birdie (-1) • Par (0) • Bogey (+1)',
    drink: 'Drankje',
    loginRequired: 'Inloggen vereist',
    loading: 'Laden...',
    pendingInvites: 'In afwachting van uitnodigingen',
    // Join Tour keys
    joinTour: 'Doe mee aan Tour',
    enterTourCode: 'Voer Tourcode in',
    getItFromHost: 'Krijg het van je tourhost',
    tourCodeLabel: 'Tourcode',
    joinTourButton: 'Doe mee aan Tour',
    verifying: 'Verifiëren...',
    or: 'of',
    scanQrCode: 'Scan QR-code',
    tapToScan: 'Tik om camera te openen en te scannen',
    invalidTourCode: 'Ongeldige Tourcode',
    startTourCostTitle: 'Start Tour Kosten',
    startTourCostMessage: 'Het starten van een tour kost 1 token. Je hebt momenteel {0} tokens.',
    insufficientTokensTitle: 'Onvoldoende Tokens',
    insufficientTokensMessage: 'Je hebt niet genoeg tokens om een tour te starten. Koop meer.',
    proceed: 'Doorgaan',
    cancel: 'Annuleren',
    failedToJoin: 'Kan niet deelnemen aan tour',
    setupTeam: 'Team Instellen',
    marketingLobbyTitle: 'Je bent binnen!',
    marketingLobbySubtitle: 'Wacht op anderen om lid te worden, stel dan je team in.',
    saveAndStart: 'Opslaan & Starten',
    saveTeam: 'Team Opslaan',
    editTeam: 'Team Bewerken',
    ready: 'Klaar!',
    howItWorks: 'Hoe het werkt',
    howItWorksStep1: '1. Krijg de tourcode van je host',
    howItWorksStep2: '2. Voer de code hierboven in',
    howItWorksStep3: '3. Maak of sluit je aan bij een team',
    howItWorksStep4: '4. Begin je avontuur!',
    teamPlay: 'Teamspel',
    teamPlayDesc: 'Bundel je krachten met vrienden of strijd tegen andere teams in epische uitdagingen!',
    // New Challenge Types
    takePhoto: 'Maak Foto',
    true: 'Waar',
    false: 'Niet Waar',
    dareCompleted: 'Ik heb het gedaan!',
    hideHint: 'Verberg Hint',
    showHint: 'Hint nodig?',
    enterAnswer: 'Voer je antwoord in...',
    correctAnswerWas: 'Antwoord:',
    // Auth Keys
    login: 'Inloggen',
    signIn: 'Aanmelden',
    googleSignIn: 'Inloggen met Google',
    signUp: 'Aanmelden',
    register: 'Registreren',
    email: 'E-mail',
    password: 'Wachtwoord',
    confirmPassword: 'Bevestig Wachtwoord',
    forgotPassword: 'Wachtwoord vergeten?',
    resetPassword: 'Wachtwoord herstellen',
    noAccount: 'Nog geen account?',
    haveAccount: 'Heb je al een account?',
    sendResetLink: 'Herstellink versturen',
    backToLogin: 'Terug naar Inloggen',
    welcomeBack: 'Welkom terug',
    loginSubtitle: 'Voer je gegevens in om je reis voort te zetten.',
    createAccount: 'Account aanmaken',
    registerSubtitle: 'Ga mee op avontuur en begin met tracken.',
    enterEmail: 'Voer je e-mail in',
    enterPassword: 'Voer je wachtwoord in',
    passwordsDoNotMatch: 'Wachtwoorden komen niet overeen',
    resetLinkSent: 'Herstellink verzonden!',
    checkEmailForReset: 'Controleer je e-mail voor de herstellink.',
    forgotPasswordSubtitle: 'Voer je e-mail in om een herstellink te ontvangen.',
    failedToLogin: 'Inloggen mislukt',
    failedToRegister: 'Registratie mislukt',
    failedToReset: 'Versturen link mislukt',
    loggingIn: 'Inloggen...',
    registering: 'Registreren...',
    sending: 'Verzenden...',
    logout: 'Uitloggen',
    resendConfirmation: 'Bevestigingsmail opnieuw verzenden',
    emailNotConfirmed: 'E-mail niet bevestigd',
    confirmationSent: 'Bevestigingsmail verzonden!',
    pleaseLoginToManageYourPersonalDetails: 'Je moet ingelogd zijn om je persoonlijke gegevens te beheren.',
    mustBeLoggedIn: 'Je moet ingelogd zijn om deze actie uit te voeren.',
    // Tour Completed
    tourCompleted: 'Tour Voltooid! 🎉',
    writeReview: 'Schrijf een Beoordeling',
    reviewSubmitted: 'Beoordeling Verzonden!',
    reviewSubmittedTitle: 'Succes',
    reviewSubmittedMessage: 'Bedankt voor je beoordeling!',
    backToHome: 'Terug naar Start',
    submitReview: 'Beoordeling Verzenden',
    reviewPlaceholder: 'Wat vond je van deze tour?',
    error: 'Fout',
    reviewSubmitError: 'Verzenden beoordeling mislukt. Probeer het opnieuw.',
    // Waiting Lobby
    greatJobTitle: 'Goed Gedaan! 🎯',
    waitingForTeams: 'Wachten op andere teams...',
    tourProgress: 'Tour Voortgang',
    teamsCompleted: '{0} van de {1} teams voltooid',
    finished: 'Voltooid!',
    inProgress: 'Bezig...',
    playersCount: '{0} spelers',
    yourTeam: 'Jouw Team',
    viewResults: 'Bekijk Resultaten',
    autoResults: 'Resultaten verschijnen automatisch als iedereen klaar is',
    saveChanges: 'Wijzigingen opslaan',
    name: 'Naam',
    profilePicture: 'Profielfoto',
    change: 'Wijzigen',
    updateSuccess: 'Profiel succesvol bijgewerkt!',
    updateError: 'Profiel bijwerken mislukt.',
    viewRulesAndScoring: 'Bekijk Regels & Scoring',
    scoring: 'Scoring',
  },
};
