// src/i18n/strings.ts
export const strings = {
  en: {
    profile: 'Profile',
    manageAccount: 'Manage your account',
    personalInfo: 'Personal Information',
    appPreferences: 'App Preferences',
    contact: 'Contact',
    terms: 'Terms & Conditions',
    faq: 'Frequently Asked Questions',
    darkMode: 'Dark Mode',
    language: 'Language',
    currentAdventure: 'YOUR CURRENT ADVENTURE',
    completed: 'Completed',
    resumeTour: 'Resume Tour',
    explore: 'Explore',
    tour: 'Tour',
    map: 'Map',
    stops: 'Stops',
    by: 'by',
    reviews: 'reviews',
    startTour: 'Start Tour',
    overview: 'Overview',
    itinerary: 'Itinerary',
    reviewsTab: 'Reviews',
    tourMap: 'Tour Map',
    topPlayers: 'Top Players this week',
    tourWideChallenges: 'Tour Wide Challenges',
    tourStops: 'Tour Stops',
    userReviews: 'User Reviews',
    // New keys for tour components
    createdBy: 'Created by',
    distance: 'Distance',
    duration: 'Duration',
    points: 'Points',
    pts: 'pts',
    aboutThisTour: 'About this tour',
    gameModes: 'Game Modes',
    challengesIncluded: 'Challenges Included',
    uniqueChallengesAcross: 'unique challenges across',
    // Profile card keys
    level: 'Level',
    explorer: 'Explorer',
    levelProgress: 'Level Progress',
    created: 'Created',
    completeAllChallengesToContinue: 'Complete all challenges to continue',
    Stop: 'Stop',
    nextLevel: 'Next level',
    yourTokens: 'Your Tokens',
    buyTokens: 'Buy Tokens',
    inviteFriends: 'Invite Friends',
    chooseTokenPackage: 'Choose a token package to continue playing tours',
    mostPopular: 'Most Popular',
    bonus: 'Bonus',
    total: 'Total',
    tokensLower: 'tokens',
    earnFreeTokens: 'Earn Free Tokens!',
    inviteFriendsDescription: 'Invite friends and earn 3 tokens for each friend who joins. Tap "Invite Friends" to get your referral link!',
    toursDone: 'Tours Done',
    totalPoints: 'Total Points',
    friends: 'Friends',
    recentAchievements: 'Recent Achievements',
    // Active Tour keys
    loadingTour: 'Loading tour...',
    tourNotFound: 'Tour not found',
    challenges: 'Challenges',
    noChallengesAtStop: 'No challenges at this stop. Enjoy the view!',
    challengeCompleted: 'Challenge Completed!',
    challengeFailed: 'Challenge Failed',
    navigate: 'Navigate',
    wrongAnswer: 'Wrong Answer',
    claimPoints: 'Claim Points',
    submitAnswer: 'Submit Answer',
    rightLocation: "You're at the right location!",
    wrongAnswerCorrectWas: 'Wrong answer! The correct answer was:',
    back: 'Back',
    finishTour: 'Finish Tour',
    next: 'Next',
    tokens: 'Tokens',
  },
  es: {
    profile: 'Perfil',
    manageAccount: 'Administrar su cuenta',
    personalInfo: 'Información personal',
    appPreferences: 'Preferencias de la app',
    contact: 'Contacto',
    terms: 'Términos y condiciones',
    faq: 'Preguntas frecuentes',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    currentAdventure: 'TU AVENTURA ACTUAL',
    completed: 'Completado',
    resumeTour: 'Continuar Tour',
    explore: 'Explorar',
    tour: 'Tour',
    map: 'Mapa',
    stops: 'Paradas',
    by: 'por',
    reviews: 'reseñas',
    startTour: 'Comenzar Tour',
    overview: 'Resumen',
    itinerary: 'Itinerario',
    reviewsTab: 'Reseñas',
    tourMap: 'Mapa del Tour',
    topPlayers: 'Mejores jugadores de la semana',
    tourWideChallenges: 'Desafíos del Tour',
    tourStops: 'Paradas del Tour',
    userReviews: 'Reseñas de usuarios',
    // New keys for tour components
    createdBy: 'Creado por',
    distance: 'Distancia',
    duration: 'Duración',
    points: 'Puntos',
    pts: 'pts',
    aboutThisTour: 'Sobre este tour',
    gameModes: 'Modos de Juego',
    challengesIncluded: 'Desafíos Incluidos',
    uniqueChallengesAcross: 'desafíos únicos en',
    // Profile card keys
    level: 'Nivel',
    explorer: 'Explorador',
    levelProgress: 'Progreso de Nivel',
    created: 'Creado',
    completeAllChallengesToContinue: 'Completa todos los desafíos para continuar',
    Stop: 'Parada',
    nextLevel: 'Siguiente nivel',
    yourTokens: 'Tus Fichas',
    buyTokens: 'Comprar Fichas',
    inviteFriends: 'Invitar Amigos',
    chooseTokenPackage: 'Elige un paquete de fichas para seguir jugando tours',
    mostPopular: 'Más Popular',
    bonus: 'Bono',
    total: 'Total',
    tokensLower: 'fichas',
    earnFreeTokens: '¡Gana Fichas Gratis!',
    inviteFriendsDescription: 'Invita a amigos y gana 3 fichas por cada amigo que se una. ¡Toca "Invitar Amigos" para obtener tu enlace de referencia!',
    toursDone: 'Tours Realizados',
    totalPoints: 'Puntos Totales',
    friends: 'Amigos',
    recentAchievements: 'Logros Recientes',
    // Active Tour keys
    loadingTour: 'Cargando tour...',
    tourNotFound: 'Tour no encontrado',
    challenges: 'Desafíos',
    noChallengesAtStop: 'No hay desafíos en esta parada. ¡Disfruta la vista!',
    challengeCompleted: '¡Desafío Completado!',
    challengeFailed: 'Desafío Fallido',
    navigate: 'Navegar',
    wrongAnswer: 'Respuesta Incorrecta',
    claimPoints: 'Reclamar Puntos',
    submitAnswer: 'Enviar Respuesta',
    rightLocation: '¡Estás en la ubicación correcta!',
    wrongAnswerCorrectWas: '¡Respuesta incorrecta! La respuesta correcta era:',
    back: 'Atrás',
    finishTour: 'Terminar Tour',
    next: 'Siguiente',
    tokens: 'Fichas',
  },
  nl: {
    profile: 'Profiel',
    manageAccount: 'Beheer uw account',
    personalInfo: 'Persoonlijke informatie',
    appPreferences: 'App-voorkeuren',
    contact: 'Contact',
    terms: 'Algemene voorwaarden',
    faq: 'Veelgestelde vragen',
    darkMode: 'Donkere modus',
    language: 'Taal',
    currentAdventure: 'JE HUIDIGE AVONTUUR',
    completed: 'Voltooid',
    resumeTour: 'Tour Hervatten',
    explore: 'Verkennen',
    tour: 'Tour',
    map: 'Kaart',
    stops: 'Stops',
    by: 'door',
    reviews: 'beoordelingen',
    startTour: 'Start Tour',
    overview: 'Overzicht',
    itinerary: 'Reisplan',
    reviewsTab: 'Beoordelingen',
    tourMap: 'Tourkaart',
    topPlayers: 'Topspelers deze week',
    tourWideChallenges: 'Tourbrede uitdagingen',
    tourStops: 'Tourstops',
    userReviews: 'Gebruikersbeoordelingen',
    // New keys for tour components
    createdBy: 'Gemaakt door',
    distance: 'Afstand',
    duration: 'Duur',
    points: 'Punten',
    pts: 'ptn',
    aboutThisTour: 'Over deze tour',
    gameModes: 'Spelmodi',
    challengesIncluded: 'Uitdagingen Inbegrepen',
    uniqueChallengesAcross: 'unieke uitdagingen over',
    // Profile card keys
    level: 'Niveau',
    explorer: 'Verkenner',
    levelProgress: 'Niveauvoortgang',
    created: 'Gemaakt',
    completeAllChallengesToContinue: 'Voltooi alle uitdagingen om door te gaan',
    Stop: 'Stop',
    nextLevel: 'Volgend niveau',
    yourTokens: 'Jouw Tokens',
    buyTokens: 'Tokens Kopen',
    inviteFriends: 'Vrienden Uitnodigen',
    chooseTokenPackage: 'Kies een tokenpakket om tours te blijven spelen',
    mostPopular: 'Meest Populair',
    bonus: 'Bonus',
    total: 'Totaal',
    tokensLower: 'tokens',
    earnFreeTokens: 'Verdien Gratis Tokens!',
    inviteFriendsDescription: 'Nodig vrienden uit en verdien 3 tokens voor elke vriend die lid wordt. Tik op "Vrienden Uitnodigen" om je verwijzingslink te krijgen!',
    toursDone: 'Tours Gedaan',
    totalPoints: 'Totaal Punten',
    friends: 'Vrienden',
    recentAchievements: 'Recente Prestaties',
    // Active Tour keys
    loadingTour: 'Tour laden...',
    tourNotFound: 'Tour niet gevonden',
    challenges: 'Uitdagingen',
    noChallengesAtStop: 'Geen uitdagingen bij deze stop. Geniet van het uitzicht!',
    challengeCompleted: 'Uitdaging Voltooid!',
    challengeFailed: 'Uitdaging Mislukt',
    navigate: 'Navigeren',
    wrongAnswer: 'Verkeerd Antwoord',
    claimPoints: 'Punten Claimen',
    submitAnswer: 'Antwoord Indienen',
    rightLocation: 'Je bent op de juiste locatie!',
    wrongAnswerCorrectWas: 'Verkeerd antwoord! Het juiste antwoord was:',
    back: 'Terug',
    finishTour: 'Tour Beëindigen',
    next: 'Volgende',
    tokens: 'Tokens',
  },
};
