// src/i18n/strings.ts
export const strings = {
  en: {
    modes: 'Modes',
    editDistance: 'Edit Distance',
    editDuration: 'Edit Duration',
    editTransportMode: 'Edit Transport Mode',
    profile: 'Profile',
    manageAccount: 'Manage your account',
    personalInfo: 'Personal Information',
    appPreferences: 'App Preferences',
    contact: 'Contact',
    terms: 'Terms & Conditions',
    faq: 'Frequently Asked Questions',
    darkMode: 'Dark Mode',
    language: 'Language',
    achievements: 'Achievements',
    totalProgress: 'Total Progress',
    unlocked: 'Unlocked',
    seeAll: 'See all',
    currentAdventure: 'YOUR CURRENT ADVENTURE',
    completed: 'Completed',
    resumeTour: 'Resume Tour',
    explore: 'Explore',
    join: 'Join',
    create: 'Create',
    tour: 'Tour',
    map: 'Map',
    stops: 'Stops',
    by: 'by',
    reviews: 'reviews',
    startTour: 'Start Tour',
    overview: 'Overview',
    itinerary: 'Itinerary',
    reviewsTab: 'Reviews',
    tourMap: 'Tour Map',
    topPlayers: 'Top Players this week',
    tourWideChallenges: 'Bonus',
    tourWideChallengesSubtitle: 'Complete these anytime during the tour!', // Added
    noTourWideChallenges: 'No tour wide challenges available.', // Added
    unknownChallengeType: 'Unknown challenge type:', // Added
    tourStops: 'Tour Stops',
    userReviews: 'User Reviews',
    // New keys for tour components
    clickToViewRoute: 'Click to view route',
    backToAllTours: 'Back to all tours',
    createdBy: 'Created by',
    distance: 'Distance',
    duration: 'Duration',
    points: 'Points',
    pts: 'pts',
    xp: 'XP',
    aboutThisTour: 'About this tour',
    gameModes: 'Game Modes',
    challengesIncluded: 'Challenges Included',
    uniqueChallengesAcross: 'unique challenges across',
    viewOnMap: 'View on Map',
    gallery: 'Gallery',
    sortBy: 'Sort by',
    newest: 'Newest',
    oldest: 'Oldest',
    highestRating: 'Highest Rated',
    lowestRating: 'Lowest Rated',
    showMore: 'Show More',
    showLess: 'Show Less',
    popularTours: 'Popular Tours',
    // Profile card keys
    level: 'Level',
    explorer: 'Explorer',
    levelProgress: 'Level Progress',
    created: 'Created',
    completeAllChallengesToContinue: 'Complete all challenges to continue',
    Stop: 'Stop',
    nextLevel: 'Next level',
    yourTokens: 'Your Tokens',
    buyTokens: 'Buy Tokens',
    inviteFriends: 'Invite Friends',
    chooseTokenPackage: 'Choose a token package to continue playing tours',
    mostPopular: 'Most Popular',
    bonus: 'Bonus',
    total: 'Total',
    tokensLower: 'tokens',
    earnFreeTokens: 'Earn Free Tokens!',
    inviteFriendsDescription: 'Invite 3 friends and earn a free token! Tap "Invite Friends" to get your referral link and start sharing!',
    yourCode: 'Your Referral Code',
    enterReferralCode: 'Enter Referral Code',
    claimReferral: 'Claim Referral',
    referralClaimed: 'Referral claimed successfully!',
    referralError: 'Failed to claim referral',
    claim: 'Claim',
    haveReferralCode: 'Have a referral code?',
    referralCodePlaceholder: 'e.g. 123 456 789',
    toursDone: 'Tours Done',
    toursCreated: 'Tours Created',
    totalPoints: 'Total Points',
    friends: 'Friends',
    recentAchievements: 'Recent Achievements',
    firstTour: 'First Tour',
    firstTourDesc: 'Congratulations on completing your first tour!',
    savedTrips: 'Saved Trips',
    mySavedTrips: 'My Saved Trips',
    saveToTrip: 'Save to Trip',
    saveToCollection: 'Save to Collection', // Added
    noCollectionsYet: 'No collections yet.', // Added
    createOne: 'Create one', // Added
    cancelCreation: 'Cancel creation', // Added
    newCollection: 'New Collection', // Added
    items: 'items', // Added
    saved: 'Saved',
    createTripList: 'Create Trip List',
    enterTripListName: 'Enter list name',
    noSavedTrips: 'No saved trips yet',
    // Active Tour keys
    createTour: 'Create Tour',
    createTourSubtitle: 'Design your own adventure',
    stepInfo: 'Basic Info',
    stepGamemodes: 'Gamemodes',
    stepStops: 'Stops',
    stepReview: 'Review',
    tourTitle: 'Tour Title',
    tourDescription: 'Description',
    tourLocation: 'Location',
    tourImage: 'Image URL',
    tourType: 'Tour Type',
    difficulty: 'Difficulty',
    selectDifficulty: 'Select Difficulty',
    selectTourType: 'Select Tour Type', // Added
    selectType: 'Select Type', // Added
    selectGenre: 'Select Genre',
    selectGameModes: 'Select Game Modes',
    addStop: 'Add Stop',
    editStop: 'Edit Stop',
    playForFree: 'Creator plays for FREE!',
    createAndStart: 'Create & Start',
    stopName: 'Stop Name',
    stopType: 'Stop Type',
    stopDescription: 'Stop Description',
    latitude: 'Latitude',
    longitude: 'Longitude',
    addChallenge: 'Add Challenge',
    addChallengeButton: 'Add Challenge',
    editChallenge: 'Edit Challenge',
    challengeTitle: 'Challenge Title',
    challengeQuestion: 'Question / Task',
    challengeAnswer: 'Answer (for Trivia)',
    challengePoints: 'Points',
    nextStep: 'Next Step',
    prevStep: 'Previous',
    finalReview: 'Final Review',
    tourCreatedSuccess: 'Tour Created Successfully!',
    fillAllFields: 'Please fill in all required fields',
    loadingTour: 'Loading tour...',
    tourNotFound: 'Tour not found',
    noToursFound: 'No tours found',
    noToursFoundDesc: 'Explore other areas or try changing your filters.', // Added
    challenges: 'Challenges',

    // Bonus Challenges Step
    stepChallenges: 'Challenges',
    bonusChallengesDesc: 'Add fun challenges that apply to the entire tour, not just specific stops. Teams can complete these at any time!',
    addBonusChallenge: 'Add Bonus Challenge',
    addBonusChallengeSubtitle: 'Create a new tour-wide challenge',
    noBonusChallenges: 'No bonus challenges added yet.',

    noChallengesAtStop: 'No challenges at this stop. Enjoy the view!',
    challengeCompleted: 'Challenge Completed!',
    challengeFailed: 'Challenge Failed',
    navigate: 'Navigate',
    expandMap: 'Expand Map',
    backToActiveTour: 'Back to Active Tour',
    wrongAnswer: 'Wrong Answer',
    claimPoints: 'Claim Points',
    submitAnswer: 'Submit Answer',
    submit: 'Submit', // Added
    verifyLocation: 'Verify Location', // Added
    rightLocation: "You're at the right location!",
    wrongAnswerCorrectWas: 'Wrong answer! The correct answer was:',
    back: 'Back',
    finishTour: 'Finish Tour',
    readyForAdventure: "Ready for Adventure?",
    enterCodeInstruction: "Enter the code shared by your team captain to join the tour.",
    orAcceptInvite: "OR ACCEPT INVITE",
    invitedBy: "Invited by",
    levelUp: "Level Up!",
    youReachedLevel: "You reached level {0}!",
    next: 'Next',
    tokens: 'Tokens',
    pubgolf: 'Pub Golf',
    info: 'Info',
    noStopDescription: 'No detailed description available for this stop.',
    // Pub Golf specific
    par: 'Par',
    sipsTaken: 'Sips taken:',
    holeInOne: 'HOLE IN ONE!',
    legendary: 'Legendary!',
    albatross: 'Albatross!',
    unreal: 'Unreal!',
    eagle: 'EAGLE!',
    amazing: 'Amazing!',
    birdie: 'Birdie!',
    greatJob: 'Great job!',
    parScore: 'PAR!',
    perfect: 'Perfect!',
    bogey: 'Bogey!',
    niceTry: 'Nice try!',
    doubleBogey: 'Double Bogey',
    tripleBogeyPlus: 'Triple Bogey+',
    evenPar: 'Even Par',
    underPar: 'Under Par!',
    overPar: 'Over Par',
    officialScorecard: 'Official Scorecard',
    totalScore: 'Total Score',
    pubGolfInstructions: 'Try to finish each drink in par or under! Lower score wins.',
    pubGolfLegend: 'Eagle (-2) • Birdie (-1) • Par (0) • Bogey (+1)',
    drink: 'Drink',
    // Team Setup
    teamSetup: 'Team Setup',
    customizeTeam: 'Customize your team for the tour!',
    teamName: 'Team Name',
    enterTeamName: 'Enter team name...',
    teamColor: 'Team Color',
    teamEmoji: 'Team Emoji',
    preview: 'Preview',
    yourTeamName: 'Your Team Name',
    createTeam: 'Create Team',
    creating: 'Creating...',
    missingInfo: 'Missing Info',
    enterTeamNameAlert: 'Please enter a team name',
    activeTourExists: 'Active Tour Exists',
    activeTourExistsMessage: 'You have an active tour. Starting a new one will cause you to lose progress. Do you want to proceed?',
    startTourCostTitle: 'Start Tour Cost',
    startTourCostMessage: 'Starting a tour costs 1 token. You currently have {0} tokens.',
    insufficientTokensTitle: 'Insufficient Tokens',
    insufficientTokensMessage: 'You do not have enough tokens to start a tour. Please buy more.',
    proceed: 'Proceed',
    cancel: 'Cancel',
    startNew: 'Start New',
    failedToCreateTeam: 'Failed to create team. Please try again.',
    loginRequired: 'Login Required',
    loading: 'Loading...',
    pendingInvites: 'Pending Invites',
    // Join Tour keys
    joinTour: 'Join Tour',
    enterTourCode: 'Enter Tour Code',
    getItFromHost: 'Get it from your tour host',
    tourCodeLabel: 'Tour Code',
    askCaptainForCode: 'Enter your tour code to begin the adventure',
    joinTourButton: 'Join Tour',
    verifying: 'Verifying...',
    or: 'or',
    scanQrCode: 'Scan QR Code',
    tapToScan: 'Tap to open camera and scan',
    invalidTourCode: 'Invalid Tour Code',
    failedToJoin: 'Failed to join tour',
    shareThisCode: 'Share this code with your team!',
    setupTeam: 'Setup Team',
    marketingLobbyTitle: "You're in!",
    marketingLobbySubtitle: 'Wait for others to join, then setup your team.',
    saveAndStart: 'Save & Start',
    saveTeam: 'Save Team',
    editTeam: 'Edit Team',
    ready: 'Ready!',
    howItWorks: 'How it works',
    howItWorksStep1: '1. Get the tour code from your host',
    howItWorksStep2: '2. Enter the code above',
    howItWorksStep3: '3. Create or join a team',
    howItWorksStep4: '4. Start your adventure!',
    teamPlay: 'Team Play',
    teamPlayDesc: 'Join forces with friends or compete against other teams in epic challenges!',
    // New Challenge Types
    uploading: 'Uploading...',
    compressingAndUploading: 'Compressing & Uploading...',
    photoUploaded: 'Photo Uploaded',
    takePhoto: 'Take Photo',
    true: 'True',
    false: 'False',
    dareCompleted: 'I did it!',
    hideHint: 'Hide Hint',
    showHint: 'Need a hint?',
    enterAnswer: 'Enter your answer...',
    correctAnswerWas: 'Answer:',
    // Auth Keys
    login: 'Login',
    signUp: 'Sign Up',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Enter your credentials to continue your journey.',
    createAccount: 'Create Account',
    registerSubtitle: 'Join the adventure and start tracking your taps.',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    passwordsDoNotMatch: 'Passwords do not match',
    resetLinkSent: 'Reset link sent!',
    checkEmailForReset: 'Check your email for the reset link.',
    forgotPasswordSubtitle: 'Enter your email to receive a password reset link.',
    failedToLogin: 'Failed to login',
    failedToRegister: 'Failed to register',
    failedToReset: 'Failed to send reset link',
    loggingIn: 'Logging in...',
    registering: 'Registering...',
    sending: 'Sending...',
    logout: 'Logout',
    resendConfirmation: 'Resend Confirmation Email',
    emailNotConfirmed: 'Email not confirmed',
    confirmationSent: 'Confirmation email sent!',
    authRequired: 'Authentication Required',
    authRequiredDesc: 'You must be logged in to access this feature. Please login or create an account to continue.',
    authenticationRequired: 'Authentication Required',
    loginToStartTour: 'You need to be logged in to start a tour.',
    signIn: 'Sign In',
    googleSignIn: 'Sign in with Google',
    pleaseLoginToManageYourPersonalDetails: 'Please login to manage your personal details.',
    mustBeLoggedIn: 'You must be logged in to perform this action.',
    // Tour Completed
    tourCompleted: 'Tour Complete! 🎉',
    writeReview: 'Write a Review',
    reviewSubmitted: 'Review Submitted!',
    reviewSubmittedTitle: 'Success',
    reviewSubmittedMessage: 'Thank you for your review!',
    backToHome: 'Back to Home',
    submitReview: 'Submit Review',
    reviewPlaceholder: 'What did you think about this tour?',
    error: 'Error',
    reviewSubmitError: 'Failed to submit review. Please try again.',
    // Waiting Lobby
    greatJobTitle: 'Great Job! 🎯',
    waitingForTeams: 'Waiting for other teams to finish...',
    tourProgress: 'Tour Progress',
    teamsCompleted: '{0} of {1} teams completed',
    finished: 'Finished!',
    inProgress: 'In progress...',
    playersCount: '{0} players',
    yourTeam: 'Your Team',
    viewResults: 'View Results',
    autoResults: 'Results will show automatically when everyone finishes',
    saveChanges: 'Save Changes',
    name: 'Name',
    profilePicture: 'Profile Picture',
    change: 'Change',
    updateSuccess: 'Profile updated successfully!',
    updateError: 'Failed to update profile.',
    viewRulesAndScoring: 'View Rules & Scoring',
    scoring: 'Scoring',
    // Create Tour Flow
    stepInfoTitle: "Let's verify the basics.",
    stepInfoSubtitle: "Give your adventure a catchy name and location.",
    titlePlaceholder: "e.g. The Hidden Gems of Paris",
    locationPlaceholder: "e.g. Paris, France",
    descPlaceholder: "What makes this tour special?",
    imagePlaceholder: "https://example.com/image.jpg",
    stepGamemodesTitle: "Choose the vibe.",
    stepGamemodesSubtitle: "Add special game modes to your tour.",
    pubGolfDescription: "A boozy adventure. Score par on drinks. Strictly 18+.",
    bingo: 'Bingo',
    bingoDescription: 'Complete challenges in a 3x3 grid. Get points for lines and a full house!',
    bingoChallenge: 'Bingo Challenge',
    bingoLinePoints: 'Points per Line',
    bingoFullPoints: 'Points for Full House',
    comingSoon: "More Coming Soon...",
    comingSoonDesc: "Bingo, Crazy 88, and more are on the way!",
    stepStopsTitle: "Map your adventure.",
    stepStopsSubtitle: "Add stops, then add challenges to them.",
    emptyStopText: "Start by adding a location",
    stepReviewTitle: "Ready to launch?",
    stepReviewSubtitle: "Review your tour card. Tap the distance or time to edit details.",
    step: "Step",
    you: "You",
    new: "New",
    km: "km",
    min: "min",
    // New strings from audit
    appearance: 'Appearance',
    brightAndClear: 'Bright and clear',
    easyOnTheEyes: 'Easy on the eyes',
    notifications: 'Notifications',
    noAchievementsYet: 'No achievements yet',
    availableBalance: 'Available Balance',
    pushNotifications: 'Push Notifications',
    emailUpdates: 'Email Updates',
    version: 'Version',
    history: 'History',
    culture: 'Culture',
    nature: 'Nature',
    mystery: 'Mystery',
    findYourNextAdventure: 'Find your next adventure',
    whereToNext: 'Where to next?',
    curatedAdventures: 'Curated adventures just for you',
    unknown: 'Unknown',
    userNotFound: 'User not found',
    socialHub: 'Social Hub',
    noFriendsYet: 'No friends yet',
    noRequests: 'No requests',
    searchFriendsText: 'Search for people by email to add them to your crew!',
    noRequestsText: 'You have no pending friend requests at the moment.',
    unknownTour: 'Unknown Tour',
    from: 'From',
    aFriend: 'a friend',
    adventure: 'Adventure',
    tracksAndTaps: 'Tracks & Taps',
    onboardingTitle1: 'Find Your Quest',
    onboardingDesc1: 'Discover hidden gems and curated tours. Your next great adventure is just a tap away.',
    onboardingTitle2: 'Level Up Your City',
    onboardingDesc2: 'Turn your city exploration into an RPG. Earn XP, unlock achievements, and dominate the leaderboard.',
    onboardingTitle3: 'Battle Your Squad',
    onboardingDesc3: 'Create a team, challenge your friends, and compete in real-time challenges for glory.',
    onboardingTitle4: 'The Pub Golf Legend',
    onboardingDesc4: 'Experience the ultimate Pub Golf mode. Track scores, hit pars, and become the legend of the night.',
    skip: 'Skip',
    startPlaying: 'Start Playing',
    tours: 'Tours',
    emailChangeNotice: 'Changing email may require re-verification.',
    security: 'Security',
    passwordHint: 'Leave blank to keep current password.',
    lobby: 'Lobby',
    calculatingResults: 'Calculating results...',
    winner: 'Winner:',
    leaderboard: 'Leaderboard',
    solo: 'Solo',
    withFriends: 'With Friends',
    permissionNeeded: 'Permission needed',
    cameraPermissionMsg: 'Sorry, we need camera roll permissions to make this work!',
    uploadFailed: 'Upload Failed',
    uploadErrorMsg: 'There was an error uploading your image. Please try again.',
    rateExperience: 'Rate Experience',
    good: 'Good!',
    okay: 'Okay',
    notGreat: 'Not great',
    addPhotos: 'Add Photos',
    selectImage: 'Select an image',
    genre: 'Genre',
    remove: 'Remove',
    edit: 'Edit',
    inviteSelected: 'Invite Selected',
    sendingInvites: 'Sending Invites...',
    selectFriendsLobby: 'Select friends to join your lobby',
    noFriendsFound: 'No friends found. Add some friends first!',

    // Create Flow - Stops
    shortDescription: "Short Description",
    shortDescriptionPlaceholder: "Brief summary for the list view...",
    detailedDescription: "Detailed Description",
    detailedDescriptionPlaceholder: "Full story, history, and details...",

    // Create Flow - Pub Golf
    isPubGolfStop: "Pub Golf Stop?",
    drinkPlaceholder: "e.g. Pint of Lager",
    parSips: "Par (Sips)",
    parPlaceholder: "e.g. 4",

    // Create Flow - Challenges
    challengeQuestionRiddle: "The Riddle",
    challengeQuestionDare: "The Dare",
    challengeQuestionPicture: "What to photograph?",
    challengeQuestionLocation: "Where exactly?",
    challengePlaceholderPicture: "e.g. Take a selfie with the statue...",
    challengePlaceholderLocation: "e.g. Stand in the center of the square...",
    challengePlaceholderDefault: "Describe the challenge...",
    challengeTitlePlaceholder: "e.g. Find the Hidden Door",
    hintOptional: "Hint (Optional)",
    hintPlaceholder: "Help them out...",

    // Create Flow - Points
    pointsRange: "(50 - 200)",

    // Create Flow - Trivia
    options: "Options",
    correctAnswerOptionA: "Correct Answer (Option A)",
    correctAnswerPlaceholder: "Type the correct answer here",
    incorrectOption: "Incorrect Option",

    // Create Flow - True/False
    correctAnswerTrue: "Correct Answer is TRUE?",
    confirmLocation: "Confirm Location",

    // Explore Screen & Filters
    filters: "Filters",
    nameAZ: "Name (A-Z)",
    any: "Any",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    cityNamePlaceholder: "City name...",
    location: "Location",
    minLabel: "Min",
    maxLabel: "Max",
    applyFilters: "Apply Filters",
    resetAllFilters: "Reset All Filters",
    inProgressBadge: "In Progress",
    levelShort: "Lvl",
    addFriendPlaceholder: "Add friend by email...",
    requests: "Requests",
    wantsToBeFriend: "Wants to be your friend",
    accept: "Accept",
    decline: "Decline",


    teamsFinishedCount: "teams finished",
    of: "of",
    noOtherTeams: "No other teams",
    otherTeams: "Other Teams",

    // Explore Screen actions
    toggleViewMode: "Map / List",
    filterTours: "Filter Tours",
    walking: "Walking",
    done: "Done",
    active: "Active",
    setupTeamToStart: "Set up your team to start!",
    everyoneIn: "Everyone in? Let's go!",
    setupTeamFirst: "Setup Team First",
    waitingForHost: "Waiting for host to start...",
    waitingForJoin: "Waiting for others to join...",
    host: "HOST",
    myTeam: "MY TEAM",

    // Profile Unique Keys
    reviewerLevel: "Reviewer Level",
    topUp: "Top Up",

    // Team Setup Unique Keys
    readyToJoin: "Ready to join!",

    // Tour Detail & Feedback Unique Keys
    noReviewsYet: "No reviews yet.",
    thanksFeedback: "Thanks for your feedback!",
    howWasExperience: "How was your experience?",
    whatImprove: "What could we improve?",
    feedbackPlaceholder: "Tell us what you didn't like...",
    submitFeedback: "Submit Feedback",

    // Genres
    nightlife: "Nightlife",
    foodie: "Food & Drink",
    romance: "Romance",
    art: "Art & Music",
    photography: "Photography",
    // Audit Findings
    noBingoCardFound: 'No Bingo Card Found',
    bingoCardTitle: 'Bingo Card',
    bingoGridTitle: 'Bingo Grid',
    bingoGridSubtitle: 'Tap a cell to add a challenge.',
    theAnswer: 'The Answer',
    riddleAnswerPlaceholder: 'What is the answer?',
    saveToCollectionTitle: 'Save to Collection',
    nameCollectionPlaceholder: 'Name your collection...',
    mapNotAvailableWeb: 'Map not available on web',
    fullHouse: 'FULL HOUSE!',
    lines: 'LINES',
  },
  es: {
    profile: 'Perfil',

    manageAccount: 'Administrar su cuenta',
    personalInfo: 'Información personal',
    appPreferences: 'Preferencias de la app',
    contact: 'Contacto',
    terms: 'Términos y condiciones',
    faq: 'Preguntas frecuentes',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    currentAdventure: 'TU AVENTURA ACTUAL',
    completed: 'Completado',
    resumeTour: 'Continuar Tour',
    explore: 'Explorar',
    join: 'Unirse',
    create: 'Crear',
    tour: 'Tour',
    map: 'Mapa',
    stops: 'Paradas',
    by: 'por',
    reviews: 'reseñas',
    startTour: 'Comenzar Tour',
    overview: 'Resumen',
    itinerary: 'Itinerario',
    reviewsTab: 'Reseñas',
    tourMap: 'Mapa del Tour',
    topPlayers: 'Mejores jugadores de la semana',
    tourWideChallenges: 'Bono',
    tourStops: 'Paradas del Tour',
    userReviews: 'Reseñas de usuarios',
    // New keys for tour components
    clickToViewRoute: 'Haga clic para ver la ruta',
    backToAllTours: 'Volver a todos los tours',
    createdBy: 'Creado por',
    distance: 'Distancia',
    duration: 'Duración',
    points: 'Puntos',
    pts: 'pts',
    xp: 'XP',
    aboutThisTour: 'Sobre este tour',
    gameModes: 'Modos de Juego',
    challengesIncluded: 'Desafíos Incluidos',
    uniqueChallengesAcross: 'desafíos únicos en',
    viewOnMap: 'Ver en Mapa',
    gallery: 'Galería',
    sortBy: 'Ordenar por',
    newest: 'Más reciente',
    oldest: 'Más antiguo',
    highestRating: 'Mejor valorado',
    lowestRating: 'Menor valorado',
    showMore: 'Mostrar más',
    showLess: 'Mostrar menos',
    popularTours: 'Tours Populares',
    // Profile card keys
    level: 'Nivel',
    explorer: 'Explorador',
    levelProgress: 'Progreso de Nivel',
    created: 'Creado',
    completeAllChallengesToContinue: 'Completa todos los desafíos para continuar',
    Stop: 'Parada',
    nextLevel: 'Siguiente nivel',
    yourTokens: 'Tus Fichas',
    buyTokens: 'Comprar Fichas',
    inviteFriends: 'Invitar Amigos',
    chooseTokenPackage: 'Elige un paquete de fichas para seguir jugando tours',
    mostPopular: 'Más Popular',
    bonus: 'Bono',
    total: 'Total',
    tokensLower: 'fichas',
    earnFreeTokens: '¡Gana Fichas Gratis!',
    inviteFriendsDescription: '¡Invita a 3 amigos y gana un token gratis! Toca en "Invitar amigos" para obtener tu enlace de referido y ¡empieza a compartir!',
    toursDone: 'Tours Realizados',
    toursCreated: 'Tours Creados',
    totalPoints: 'Puntos Totales',
    friends: 'Amigos',
    recentAchievements: 'Logros Recientes',
    firstTour: 'Primer Tour',
    firstTourDesc: '¡Felicidades por completar tu primer tour!',
    savedTrips: 'Viajes Guardados',
    mySavedTrips: 'Mis Viajes',
    saveToTrip: 'Guardar en Viaje',
    saved: 'Guardado',
    createTripList: 'Crear Lista de Viaje',
    enterTripListName: 'Nombre de la lista',
    noSavedTrips: 'Aún no hay viajes guardados',
    // Active Tour keys
    difficulty: 'Dificultad',
    selectDifficulty: 'Seleccionar Dificultad',
    selectTourType: 'Seleccionar Tipo de Tour', // Added
    selectType: 'Seleccionar Tipo', // Added
    selectGenre: 'Seleccionar Género',
    selectGameModes: 'Seleccionar Modos de Juego',
    loadingTour: 'Cargando tour...',
    tourNotFound: 'Tour no encontrado',
    noToursFound: 'No se encontraron tours',
    noToursFoundDesc: 'Explora otras áreas o intenta cambiar tus filtros.', // Added
    challenges: 'Desafíos',

    // Bonus Challenges Step
    stepChallenges: 'Desafíos',
    bonusChallengesDesc: 'Añade desafíos divertidos que se apliquen a todo el tour, no solo a paradas específicas. ¡Los equipos pueden completarlos en cualquier momento!',
    addBonusChallenge: 'Añadir Desafío Extra',
    addBonusChallengeSubtitle: 'Crear un nuevo desafío para todo el tour',
    noBonusChallenges: 'Aún no se han añadido desafíos extra.',

    noChallengesAtStop: 'No hay desafíos en esta parada. ¡Disfruta la vista!',
    challengeCompleted: '¡Desafío Completado!',
    challengeFailed: 'Desafío Fallido',
    navigate: 'Navegar',
    wrongAnswer: 'Respuesta Incorrecta',
    claimPoints: 'Reclamar Puntos',
    submitAnswer: 'Enviar Respuesta',
    submit: 'Enviar', // Added
    verifyLocation: 'Verificar Ubicación', // Added
    rightLocation: '¡Estás en la ubicación correcta!',
    wrongAnswerCorrectWas: '¡Respuesta incorrecta! La respuesta correcta era:',
    back: 'Atrás',
    finishTour: 'Terminar Tour',
    next: 'Siguiente',
    tokens: 'Fichas',
    pubgolf: 'Pub Golf',
    info: 'Info',
    noStopDescription: 'No hay información detallada disponible para esta parada.',
    // Pub Golf specific
    par: 'Par',
    sipsTaken: 'Sorbos tomados:',
    holeInOne: '¡HOYO EN UNO!',
    legendary: '¡Legendario!',
    albatross: '¡Albatros!',
    unreal: '¡Irreal!',
    eagle: '¡ÁGUILA!',
    amazing: '¡Increíble!',
    birdie: '¡Pajarito!',
    greatJob: '¡Gran trabajo!',
    parScore: '¡PAR!',
    perfect: '¡Perfecto!',
    bogey: '¡Bogey!',
    niceTry: '¡Buen intento!',
    doubleBogey: 'Doble Bogey',
    tripleBogeyPlus: 'Triple Bogey+',
    evenPar: 'Par',
    underPar: '¡Bajo Par!',
    overPar: 'Sobre Par',
    officialScorecard: 'Tarjeta de Puntuación Oficial',
    totalScore: 'Puntuación Total',
    pubGolfInstructions: '¡Intenta terminar cada bebida en par o menos! La puntuación más baja gana.',
    pubGolfLegend: 'Águila (-2) • Pajarito (-1) • Par (0) • Bogey (+1)',
    drink: 'Bebida',
    loginRequired: 'Inicio de sesión obligatorio',
    loading: 'Cargando...',
    pendingInvites: 'Invitaciones Pendientes',
    // Join Tour keys
    joinTour: 'Unirse al Tour',
    enterTourCode: 'Ingresar Código del Tour',
    getItFromHost: 'Consíguelo de tu anfitrión',
    tourCodeLabel: 'Código del Tour',
    askCaptainForCode: 'Ingresa tu código de tour para comenzar la aventura',
    joinTourButton: 'Unirse al Tour',
    verifying: 'Verificando...',
    or: 'o',
    scanQrCode: 'Escanear Código QR',
    tapToScan: 'Toca para abrir cámara y escanear',
    invalidTourCode: 'Código del Tour Inválido',
    startTourCostTitle: 'Costo del Tour',
    startTourCostMessage: 'Iniciar un tour cuesta 1 ficha. Actualmente tienes {0} fichas.',
    insufficientTokensTitle: 'Fichas Insuficientes',
    insufficientTokensMessage: 'No tienes suficientes fichas para iniciar un tour. Por favor compra más.',
    proceed: 'Continuar',
    cancel: 'Cancelar',
    failedToJoin: 'Error al unirse al tour',
    setupTeam: 'Configurar Equipo',
    marketingLobbyTitle: '¡Estás dentro!',
    marketingLobbySubtitle: 'Espera a que otros se unan, luego configura tu equipo.',
    saveAndStart: 'Guardar y Empezar',
    saveTeam: 'Guardar Equipo',
    editTeam: 'Editar Equipo',
    ready: '¡Listo!',
    howItWorks: 'Cómo funciona',
    howItWorksStep1: '1. Obtén el código del tour de tu anfitrión',
    howItWorksStep2: '2. Ingresa el código arriba',
    howItWorksStep3: '3. Crea o únete a un equipo',
    howItWorksStep4: '4. ¡Comienza tu aventura!',
    teamPlay: 'Juego en Equipo',
    teamPlayDesc: '¡Une fuerzas con amigos o compite contra otros equipos en desafíos épicos!',
    // New Challenge Types
    takePhoto: 'Tomar Foto',
    compressingAndUploading: 'Comprimiendo y Subiendo...',
    photoUploaded: 'Foto Subida',
    true: 'Verdadero',
    false: 'Falso',
    dareCompleted: '¡Lo hice!',
    hideHint: 'Ocultar Pista',
    showHint: '¿Necesitas una pista?',
    enterAnswer: 'Ingresa tu respuesta...',
    correctAnswerWas: 'Respuesta:',
    // Auth Keys
    login: 'Iniciar sesión',
    signIn: 'Ingresar',
    googleSignIn: 'Iniciar con Google',
    signUp: 'Registrarse',
    register: 'Registrar',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    resetPassword: 'Restablecer contraseña',
    noAccount: '¿No tienes una cuenta?',
    haveAccount: '¿Ya tienes una cuenta?',
    sendResetLink: 'Enviar enlace',
    backToLogin: 'Volver a iniciar sesión',
    welcomeBack: 'Bienvenido de nuevo',
    loginSubtitle: 'Ingresa tus credenciales para continuar tu viaje.',
    createAccount: 'Crear cuenta',
    registerSubtitle: 'Únete a la aventura y comienza tu seguimiento.',
    enterEmail: 'Ingresa tu correo',
    enterPassword: 'Ingresa tu contraseña',
    passwordsDoNotMatch: 'Las contraseñas no coinciden',
    resetLinkSent: '¡Enlace enviado!',
    checkEmailForReset: 'Revisa tu correo para el enlace de restablecimiento.',
    forgotPasswordSubtitle: 'Ingresa tu correo para recibir un enlace de recuperación.',
    failedToLogin: 'Error al iniciar sesión',
    failedToRegister: 'Error al registrarse',
    failedToReset: 'Error al enviar enlace',
    loggingIn: 'Iniciando sesión...',
    registering: 'Registrando...',
    sending: 'Enviando...',
    logout: 'Cerrar sesión',
    resendConfirmation: 'Reenviar correo de confirmación',
    emailNotConfirmed: 'Correo no confirmado',
    confirmationSent: '¡Correo de confirmación enviado!',
    pleaseLoginToManageYourPersonalDetails: 'Por favor, inicia sesión para gestionar tus datos personales.',
    authRequired: 'Autenticación Requerida',
    authRequiredDesc: 'Debes iniciar sesión para acceder a esta función. Por favor ingresa o crea una cuenta para continuar.',
    levelUp: '¡Subiste de Nivel!',
    youReachedLevel: 'Alcanzaste el Nivel {0}',
    // Tour Completed
    tourCompleted: '¡Tour Completado! 🎉',
    writeReview: 'Escribir Reseña',
    reviewSubmitted: '¡Reseña Enviada!',
    reviewSubmittedTitle: 'Éxito',
    reviewSubmittedMessage: '¡Gracias por tu reseña!',
    backToHome: 'Volver al Inicio',
    submitReview: 'Enviar Reseña',
    reviewPlaceholder: '¿Qué te pareció este tour?',
    error: 'Error',
    reviewSubmitError: 'Error al enviar la reseña. Por favor inténtalo de nuevo.',
    // Waiting Lobby
    greatJobTitle: '¡Buen Trabajo! 🎯',
    waitingForTeams: 'Esperando a que otros equipos terminen...',
    tourProgress: 'Progreso del Tour',
    teamsCompleted: '{0} de {1} equipos completados',
    finished: '¡Terminado!',
    inProgress: 'En progreso...',
    playersCount: '{0} jugadores',
    yourTeam: 'Tu Equipo',
    viewResults: 'Ver Resultados',
    autoResults: 'Los resultados se mostrarán automáticamente cuando todos terminen',
    tourWideChallengesSubtitle: '¡Completa estos en cualquier momento durante el tour!',
    noTourWideChallenges: 'No hay desafíos de tour disponibles.',
    unknownChallengeType: 'Tipo de desafío desconocido:',
    // Create Flow & Challenges
    stopName: 'Nombre del Lugar',
    shortDescription: 'Descripción Corta (Vista de Lista)',
    shortDescriptionPlaceholder: 'Breve resumen...',
    detailedDescription: 'Descripción Detallada (Vista Completa)',
    detailedDescriptionPlaceholder: 'Cuenta la historia completa...',
    tourImage: 'Imagen del Tour',
    tourType: 'Tipo de Tour',
    imagePlaceholder: 'Toca para añadir imagen',
    stopType: 'Tipo de Parada',
    isPubGolfStop: '¿Parada de Pub Golf?',
    drinkPlaceholder: 'ej. Pinta de Lager',
    parSips: 'Par (Sorbos)',
    parPlaceholder: '3',
    challengeTitle: 'Título',
    challengeTitlePlaceholder: 'ej. Encuentra la Puerta Oculta',
    challengeQuestion: 'Pregunta',
    challengeQuestionRiddle: 'El Acertijo',
    challengeQuestionDare: 'El Reto',
    challengeQuestionPicture: '¿Qué fotografiar?',
    challengeQuestionLocation: '¿Dónde exactamente?',
    challengePlaceholderPicture: 'ej. Tómate una selfie con la estatua...',
    challengePlaceholderLocation: 'ej. Párate en el centro de la plaza...',
    challengePlaceholderDefault: 'Describe el desafío...',
    hintOptional: 'Pista (Opcional)',
    hintPlaceholder: 'Ayúdalos...',
    pointsRange: '(50 - 200)',
    options: 'Opciones',
    correctAnswerOptionA: 'Respuesta Correcta (Opción A)',
    correctAnswerPlaceholder: 'Escribe la respuesta correcta aquí',
    incorrectOption: 'Opción Incorrecta',
    correctAnswerTrue: '¿La respuesta correcta es VERDADERO?',
    confirmLocation: 'Confirmar Ubicación',
    // Challenge Types
    trivia: 'Trivia',
    trueFalse: 'Verdadero/Falso',
    photo: 'Foto',
    riddle: 'Acertijo',
    location: 'Ubicación',
    checkIn: 'Check-in',
    dare: 'Reto',
    saveChanges: 'Guardar cambios',
    name: 'Nombre',
    profilePicture: 'Foto de perfil',
    change: 'Cambiar',
    updateSuccess: '¡Perfil actualizado con éxito!',
    updateError: 'Error al actualizar el perfil.',
    viewRulesAndScoring: 'Ver Reglas y Puntuación',
    scoring: 'Puntuación',
    // New strings from audit
    appearance: 'Apariencia',
    brightAndClear: 'Brillante y claro',
    easyOnTheEyes: 'Agradable a la vista',
    notifications: 'Notificaciones',
    lobby: 'Sala de Espera',
    availableBalance: 'Saldo Disponible',
    pushNotifications: 'Notificaciones Push',
    emailUpdates: 'Actualizaciones por correo',
    readyForAdventure: "¿Listo para la aventura?",
    enterCodeInstruction: "Ingresa el código compartido por tu capitán para unirte al tour.",
    orAcceptInvite: "O ACEPTAR INVITACIÓN",
    invitedBy: "Invitado por",
    version: 'Versión',
    history: 'Historia',
    culture: 'Cultura',
    nature: 'Naturaleza',
    mystery: 'Misterio',
    findYourNextAdventure: 'Encuentra tu próxima aventura',
    whereToNext: '¿A dónde vamos?',
    curatedAdventures: 'Aventuras seleccionadas solo para ti',
    unknown: 'Desconocido',
    userNotFound: 'Usuario no encontrado',
    socialHub: 'Social Hub',
    noFriendsYet: 'Aún no tienes amigos',
    noRequests: 'Sin solicitudes',
    searchFriendsText: '¡Busca amigos por correo para agregarlos a tu equipo!',
    noRequestsText: 'No tienes solicitudes pendientes.',
    unknownTour: 'Tour Desconocido',
    from: 'De',
    aFriend: 'un amigo',
    adventure: 'Aventura',
    tracksAndTaps: 'Tracks & Taps',
    onboardingTitle1: 'Encuentra tu Misión',
    onboardingDesc1: 'Descubre joyas ocultas y tours curados.',
    onboardingTitle2: 'Sube de Nivel tu Ciudad',
    onboardingDesc2: 'Convierte tu ciudad en un RPG. Gana XP y logros.',
    onboardingTitle3: 'Batalla con tu Escuadrón',
    onboardingDesc3: 'Crea un equipo y compite con amigos.',
    onboardingTitle4: 'La Leyenda del Pub Golf',
    onboardingDesc4: 'Experimenta el modo Pub Golf definitivo.',
    skip: 'Saltar',
    startPlaying: 'Empezar a Jugar',
    tours: 'Tours',
    emailChangeNotice: 'Cambiar el correo puede requerir nueva verificación.',
    security: 'Seguridad',
    passwordHint: 'Deja en blanco para mantener contraseña actual.',
    calculatingResults: 'Calculando resultados...',
    winner: 'Ganador:',
    leaderboard: 'Tabla de Clasificación',
    solo: 'Solo',
    withFriends: 'Con Amigos',
    permissionNeeded: 'Permiso necesario',
    cameraPermissionMsg: '¡Necesitamos acceso a la galería!',
    uploadFailed: 'Carga fallida',
    uploadErrorMsg: 'Error al cargar la imagen. Inténtalo de nuevo.',
    rateExperience: 'Calificar Experiencia',
    good: '¡Bien!',
    okay: 'Bien',
    notGreat: 'No muy bien',
    addPhotos: 'Añadir Fotos',
    selectImage: 'Selecciona imagen',
    genre: 'Género',
    remove: 'Eliminar',
    edit: 'Editar',
    inviteSelected: 'Invitar Seleccionados',
    sendingInvites: 'Enviando...',
    selectFriendsLobby: 'Selecciona amigos para tu lobby',
    noFriendsFound: 'No se encontraron amigos.',
    noAchievementsYet: 'Aún no hay logros',



    // Explore Screen & Filters
    filters: "Filtros",
    nameAZ: "Nombre (A-Z)",
    any: "Cualquiera",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    cityNamePlaceholder: "Nombre de la ciudad...",
    minLabel: "Mín",
    maxLabel: "Máx",
    applyFilters: "Aplicar Filtros",
    resetAllFilters: "Restablecer Filtros",
    inProgressBadge: "En Progreso",
    levelShort: "Nvl",
    addFriendPlaceholder: "Añadir amigo por correo...",
    requests: "Solicitudes",
    wantsToBeFriend: "Quiere ser tu amigo",
    accept: "Aceptar",
    decline: "Rechazar",

    teamsFinishedCount: "equipos terminaron",
    of: "de",
    noOtherTeams: "No hay otros equipos",
    otherTeams: "Otros Equipos",
    walking: "Caminando",
    done: "Hecho",
    active: "Activo",
    setupTeamToStart: "¡Configura tu equipo para empezar!",
    everyoneIn: "¿Todos listos? ¡Vamos!",
    setupTeamFirst: "Configura el Equipo Primero",
    waitingForHost: "Esperando al anfitrión...",
    waitingForJoin: "Esperando a otros...",
    host: "ANFITRIÓN",
    myTeam: "MI EQUIPO",

    // Profile Unique Keys
    reviewerLevel: "Nivel de Reseñador",
    topUp: "Recargar",
    readyToJoin: "¡Listo para unirse!",

    // Tour Detail & Feedback Unique Keys
    noReviewsYet: "Aún no hay reseñas.",
    thanksFeedback: "¡Gracias por tus comentarios!",
    howWasExperience: "¿Cómo fue tu experiencia?",
    whatImprove: "¿Qué podríamos mejorar?",
    feedbackPlaceholder: "Cuéntanos qué no te gustó...",
    submitFeedback: "Enviar Comentarios",

    // Genres
    nightlife: "Vida Nocturna",
    foodie: "Comida y Bebida",
    romance: "Romance",
    art: "Arte y Música",
    photography: "Fotografía",
    // Audit Findings
    noBingoCardFound: 'No se encontró tarjeta de Bingo',
    bingoCardTitle: 'Tarjeta de Bingo',
    bingoGridTitle: 'Cuadrícula de Bingo',
    bingoGridSubtitle: 'Toca una celda para añadir un desafío.',
    theAnswer: 'La Respuesta',
    riddleAnswerPlaceholder: '¿Cuál es la respuesta?',
    saveToCollectionTitle: 'Guardar en Colección',
    nameCollectionPlaceholder: 'Nombra tu colección...',
    mapNotAvailableWeb: 'Mapa no disponible en web',
    fullHouse: '¡PLENO!',
    lines: 'LÍNEAS',
  },
  nl: {
    profile: 'Profiel',
    manageAccount: 'Beheer uw account',
    personalInfo: 'Persoonlijke informatie',
    appPreferences: 'App-voorkeuren',
    contact: 'Contact',
    terms: 'Algemene voorwaarden',
    faq: 'Veelgestelde vragen',
    darkMode: 'Donkere modus',
    language: 'Taal',
    currentAdventure: 'JE HUIDIGE AVONTUUR',
    completed: 'Voltooid',
    resumeTour: 'Tour Hervatten',
    explore: 'Verkennen',
    join: 'Meedoen',
    create: 'Maken',
    tour: 'Tour',
    map: 'Kaart',
    stops: 'Stops',
    by: 'door',
    reviews: 'beoordelingen',
    startTour: 'Start Tour',
    overview: 'Overzicht',
    itinerary: 'Reisplan',
    reviewsTab: 'Beoordelingen',
    tourMap: 'Tourkaart',
    topPlayers: 'Topspelers deze week',
    tourWideChallenges: 'Tourbrede uitdagingen',
    tourStops: 'Tourstops',
    userReviews: 'Gebruikersbeoordelingen',
    // New keys for tour components
    clickToViewRoute: 'Klik om route te bekijken',
    backToAllTours: 'Terug naar alle tours',
    createdBy: 'Gemaakt door',
    distance: 'Afstand',
    duration: 'Duur',
    points: 'Punten',
    pts: 'ptn',
    xp: 'XP',
    aboutThisTour: 'Over deze tour',
    gameModes: 'Spelmodi',
    challengesIncluded: 'Uitdagingen Inbegrepen',
    uniqueChallengesAcross: 'unieke uitdagingen over',
    viewOnMap: 'Bekijk op Kaart',
    gallery: 'Galerij',
    sortBy: 'Sorteer op',
    newest: 'Nieuwste',
    oldest: 'Oudste',
    highestRating: 'Hoogst gewaardeerd',
    lowestRating: 'Laagst gewaardeerd',
    showMore: 'Toon meer',
    showLess: 'Toon minder',
    popularTours: 'Populaire Tours',
    // Profile card keys
    level: 'Niveau',
    explorer: 'Verkenner',
    levelProgress: 'Niveauvoortgang',
    created: 'Gemaakt',
    completeAllChallengesToContinue: 'Voltooi alle uitdagingen om door te gaan',
    Stop: 'Stop',
    nextLevel: 'Volgend niveau',
    yourTokens: 'Jouw Tokens',
    buyTokens: 'Tokens Kopen',
    inviteFriends: 'Vrienden Uitnodigen',
    chooseTokenPackage: 'Kies een tokenpakket om tours te blijven spelen',
    mostPopular: 'Meest Populair',
    bonus: 'Bonus',
    total: 'Totaal',
    tokensLower: 'tokens',
    earnFreeTokens: 'Verdien Gratis Tokens!',
    inviteFriendsDescription: 'Nodig 3 vrienden uit en verdien een gratis munt! Tik op "Vrienden uitnodigen" voor je persoonlijke link en begin met delen!',
    toursDone: 'Tours Gedaan',
    toursCreated: 'Tours Gemaakt',
    totalPoints: 'Totaal Punten',
    friends: 'Vrienden',
    recentAchievements: 'Recente Prestaties',
    // Active Tour keys
    difficulty: 'Moeilijkheidsgraad',
    selectDifficulty: 'Selecteer Moeilijkheidsgraad',
    selectGenre: 'Selecteer Genre',
    selectGameModes: 'Selecteer Spelmodi',
    loadingTour: 'Tour laden...',
    tourNotFound: 'Tour niet gevonden',
    challenges: 'Uitdagingen',
    noChallengesAtStop: 'Geen uitdagingen bij deze stop. Geniet van het uitzicht!',
    challengeCompleted: 'Uitdaging Voltooid!',
    challengeFailed: 'Uitdaging Mislukt',
    navigate: 'Navigeren',
    wrongAnswer: 'Verkeerd Antwoord',
    claimPoints: 'Punten Claimen',
    submitAnswer: 'Antwoord Indienen',
    rightLocation: 'Je bent op de juiste locatie!',
    wrongAnswerCorrectWas: 'Verkeerd antwoord! Het juiste antwoord was:',
    back: 'Terug',
    finishTour: 'Tour Beëindigen',
    next: 'Volgende',
    tokens: 'Tokens',
    pubgolf: 'Pub Golf',
    info: 'Info',
    noStopDescription: 'Geen gedetailleerde informatie beschikbaar voor deze stop.',
    // Pub Golf specific
    par: 'Par',
    sipsTaken: 'Slokken genomen:',
    holeInOne: 'HOLE IN ONE!',
    legendary: 'Legendarisch!',
    albatross: 'Albatros!',
    unreal: 'Onwerkelijk!',
    eagle: 'EAGLE!',
    amazing: 'Geweldig!',
    birdie: 'Birdie!',
    greatJob: 'Goed gedaan!',
    parScore: 'PAR!',
    perfect: 'Perfect!',
    bogey: 'Bogey!',
    niceTry: 'Goed geprobeerd!',
    doubleBogey: 'Dubbele Bogey',
    tripleBogeyPlus: 'Drievoudige Bogey+',
    evenPar: 'Even Par',
    underPar: 'Onder Par!',
    overPar: 'Boven Par',
    officialScorecard: 'Officiële Scorekaart',
    totalScore: 'Totale Score',
    pubGolfInstructions: 'Probeer elk drankje in par of minder te eindigen! Lagere score wint.',
    pubGolfLegend: 'Eagle (-2) • Birdie (-1) • Par (0) • Bogey (+1)',
    drink: 'Drankje',
    loginRequired: 'Inloggen vereist',
    loading: 'Laden...',
    pendingInvites: 'In afwachting van uitnodigingen',
    // Join Tour keys
    joinTour: 'Doe mee aan Tour',
    enterTourCode: 'Voer Tourcode in',
    getItFromHost: 'Krijg het van je tourhost',
    tourCodeLabel: 'Tourcode',
    askCaptainForCode: 'Voer je tourcode in om het avontuur te beginnen',
    joinTourButton: 'Doe mee aan Tour',
    verifying: 'Verifiëren...',
    or: 'of',
    scanQrCode: 'Scan QR-code',
    tapToScan: 'Tik om camera te openen en te scannen',
    invalidTourCode: 'Ongeldige Tourcode',
    startTourCostTitle: 'Start Tour Kosten',
    startTourCostMessage: 'Het starten van een tour kost 1 token. Je hebt momenteel {0} tokens.',
    insufficientTokensTitle: 'Onvoldoende Tokens',
    insufficientTokensMessage: 'Je hebt niet genoeg tokens om een tour te starten. Koop meer.',
    proceed: 'Doorgaan',
    cancel: 'Annuleren',
    failedToJoin: 'Kan niet deelnemen aan tour',
    setupTeam: 'Team Instellen',
    marketingLobbyTitle: 'Je bent binnen!',
    marketingLobbySubtitle: 'Wacht op anderen om lid te worden, stel dan je team in.',
    saveAndStart: 'Opslaan & Starten',
    saveTeam: 'Team Opslaan',
    editTeam: 'Team Bewerken',
    ready: 'Klaar!',
    howItWorks: 'Hoe het werkt',
    howItWorksStep1: '1. Krijg de tourcode van je host',
    howItWorksStep2: '2. Voer de code hierboven in',
    howItWorksStep3: '3. Maak of sluit je aan bij een team',
    howItWorksStep4: '4. Begin je avontuur!',
    teamPlay: 'Teamspel',
    teamPlayDesc: 'Bundel je krachten met vrienden of strijd tegen andere teams in epische uitdagingen!',
    // New Challenge Types
    takePhoto: 'Maak Foto',
    compressingAndUploading: 'Comprimeren & Uploaden...',
    photoUploaded: 'Foto Geüpload',
    true: 'Waar',
    false: 'Niet Waar',
    dareCompleted: 'Ik heb het gedaan!',
    hideHint: 'Verberg Hint',
    showHint: 'Hint nodig?',
    enterAnswer: 'Voer je antwoord in...',
    correctAnswerWas: 'Antwoord:',
    // Auth Keys
    login: 'Inloggen',
    signIn: 'Aanmelden',
    googleSignIn: 'Inloggen met Google',
    signUp: 'Aanmelden',
    register: 'Registreren',
    email: 'E-mail',
    password: 'Wachtwoord',
    confirmPassword: 'Bevestig Wachtwoord',
    forgotPassword: 'Wachtwoord vergeten?',
    resetPassword: 'Wachtwoord herstellen',
    noAccount: 'Nog geen account?',
    haveAccount: 'Heb je al een account?',
    sendResetLink: 'Herstellink versturen',
    backToLogin: 'Terug naar Inloggen',
    welcomeBack: 'Welkom terug',
    loginSubtitle: 'Voer je gegevens in om je reis voort te zetten.',
    createAccount: 'Account aanmaken',
    registerSubtitle: 'Ga mee op avontuur en begin met tracken.',
    enterEmail: 'Voer je e-mail in',
    enterPassword: 'Voer je wachtwoord in',
    passwordsDoNotMatch: 'Wachtwoorden komen niet overeen',
    resetLinkSent: 'Herstellink verzonden!',
    checkEmailForReset: 'Controleer je e-mail voor de herstellink.',
    forgotPasswordSubtitle: 'Voer je e-mail in om een herstellink te ontvangen.',
    failedToLogin: 'Inloggen mislukt',
    failedToRegister: 'Registratie mislukt',
    failedToReset: 'Versturen link mislukt',
    loggingIn: 'Inloggen...',
    registering: 'Registreren...',
    sending: 'Verzenden...',
    logout: 'Uitloggen',
    resendConfirmation: 'Bevestigingsmail opnieuw verzenden',
    emailNotConfirmed: 'E-mail niet bevestigd',
    confirmationSent: 'Bevestigingsmail verzonden!',
    pleaseLoginToManageYourPersonalDetails: 'Je moet ingelogd zijn om je persoonlijke gegevens te beheren.',
    authRequired: 'Authenticatie Vereist',
    authRequiredDesc: 'Je moet ingelogd zijn om toegang te krijgen tot deze functie. Log in of maak een account aan om door te gaan.',
    levelUp: 'Level Omhoog!',
    youReachedLevel: 'Je hebt Level {0} bereikt',
    // Tour Completed
    tourCompleted: 'Tour Voltooid! 🎉',
    writeReview: 'Schrijf een Beoordeling',
    reviewSubmitted: 'Beoordeling Verzonden!',
    reviewSubmittedTitle: 'Succes',
    reviewSubmittedMessage: 'Bedankt voor je beoordeling!',
    backToHome: 'Terug naar Start',
    submitReview: 'Beoordeling Verzenden',
    reviewPlaceholder: 'Wat vond je van deze tour?',
    error: 'Fout',
    reviewSubmitError: 'Verzenden beoordeling mislukt. Probeer het opnieuw.',
    // Waiting Lobby
    greatJobTitle: 'Goed Gedaan! 🎯',
    waitingForTeams: 'Wachten op andere teams...',
    tourProgress: 'Tour Voortgang',
    teamsCompleted: '{0} van de {1} teams voltooid',
    finished: 'Voltooid!',
    inProgress: 'Bezig...',
    playersCount: '{0} spelers',
    yourTeam: 'Jouw Team',
    viewResults: 'Bekijk Resultaten',
    autoResults: 'Resultaten verschijnen automatisch als iedereen klaar is',
    tourWideChallengesSubtitle: 'Voltooi deze op elk moment tijdens de tour!',
    noTourWideChallenges: 'Geen tourbrede uitdagingen beschikbaar.',
    unknownChallengeType: 'Onbekend uitdagingstype:',
    // Create Flow & Challenges
    stopName: 'Locatienaam',
    shortDescription: 'Korte Beschrijving (Lijstweergave)',
    shortDescriptionPlaceholder: 'Korte samenvatting...',
    detailedDescription: 'Gedetailleerde Beschrijving (Volledige Weergave)',
    detailedDescriptionPlaceholder: 'Vertel het hele verhaal...',
    tourImage: 'Tour Afbeelding',
    imagePlaceholder: 'Tik om afbeelding toe te voegen',
    stopType: 'Stop Type',
    isPubGolfStop: 'Pub Golf Stop?',
    drinkPlaceholder: 'bijv. Pint Lager',
    parSips: 'Par (Slokken)',
    parPlaceholder: '3',
    challengeTitle: 'Titel',
    challengeTitlePlaceholder: 'bijv. Vind de Verborgen Deur',
    challengeQuestion: 'Vraag',
    challengeQuestionRiddle: 'Het Raadsel',
    challengeQuestionDare: 'De Uitdaging',
    challengeQuestionPicture: 'Wat te fotograferen?',
    challengeQuestionLocation: 'Waar precies?',
    challengePlaceholderPicture: 'bijv. Maak een selfie met het standbeeld...',
    challengePlaceholderLocation: 'bijv. Sta in het midden van het plein...',
    challengePlaceholderDefault: 'Beschrijf de uitdaging...',
    hintOptional: 'Hint (Optioneel)',
    hintPlaceholder: 'Help ze een handje...',
    pointsRange: '(50 - 200)',
    options: 'Opties',
    correctAnswerOptionA: 'Juiste Antwoord (Optie A)',
    correctAnswerPlaceholder: 'Typ hier het juiste antwoord',
    incorrectOption: 'Onjuiste Optie',
    correctAnswerTrue: 'Is het juiste antwoord WAAR?',
    confirmLocation: 'Locatie Bevestigen',
    // Challenge Types
    trivia: 'Trivia',
    trueFalse: 'Waar/Niet Waar',
    photo: 'Foto',
    riddle: 'Raadsel',
    location: 'Locatie',
    checkIn: 'Check-in',
    dare: 'Durven',
    saveChanges: 'Wijzigingen opslaan',
    name: 'Naam',
    profilePicture: 'Profielfoto',
    change: 'Wijzigen',
    updateSuccess: 'Profiel succesvol bijgewerkt!',
    updateError: 'Profiel bijwerken mislukt.',
    viewRulesAndScoring: 'Bekijk Regels & Scoring',
    scoring: 'Scoring',
    // New strings from audit
    appearance: 'Uiterlijk',
    brightAndClear: 'Helder en duidelijk',
    easyOnTheEyes: 'Rustig voor de ogen',
    notifications: 'Meldingen',
    lobby: 'Lobby',
    availableBalance: 'Beschikbaar Saldo',
    pushNotifications: 'Pushmeldingen',
    emailUpdates: 'E-mailupdates',
    version: 'Versie',
    history: 'Geschiedenis',
    culture: 'Cultuur',
    nature: 'Natuur',
    mystery: 'Mysterie',
    findYourNextAdventure: 'Vind je volgende avontuur',
    whereToNext: 'Waarheen nu?',
    curatedAdventures: 'Gecureerde avonturen speciaal voor jou',
    unknown: 'Onbekend',
    userNotFound: 'Gebruiker niet gevonden',
    socialHub: 'Sociale Hub',
    noFriendsYet: 'Nog geen vrienden',
    noRequests: 'Geen verzoeken',
    searchFriendsText: 'Zoek op e-mail om vrienden uit te nodigen!',
    noRequestsText: 'Geen openstaande verzoeken.',
    unknownTour: 'Onbekende Tour',
    from: 'Van',
    aFriend: 'een vriend',
    adventure: 'Avontuur',
    tracksAndTaps: 'Tracks & Taps',
    onboardingTitle1: 'Vind je Queeste',
    onboardingDesc1: 'Ontdek verborgen pareltjes.',
    onboardingTitle2: 'Level Up je Stad',
    onboardingDesc2: 'Verander je stad in een RPG. Verdien XP.',
    onboardingTitle3: 'Strijd met je Squad',
    onboardingDesc3: 'Maak een team en daag vrienden uit.',
    onboardingTitle4: 'De Pub Golf Legende',
    onboardingDesc4: 'Ervaar de ultieme Pub Golf modus.',
    skip: 'Overslaan',
    startPlaying: 'Start met Spelen',
    tours: 'Tours',
    emailChangeNotice: 'E-mail wijzigen vereist mogelijk herverificatie.',
    security: 'Beveiliging',
    passwordHint: 'Laat leeg om huidig wachtwoord te behouden.',
    calculatingResults: 'Resultaten berekenen...',
    winner: 'Winnaar:',
    leaderboard: 'Scorebord',
    solo: 'Solo',
    withFriends: 'Met Vrienden',
    permissionNeeded: 'Toestemming nodig',
    cameraPermissionMsg: 'We hebben toegang tot je fotorol nodig!',
    uploadFailed: 'Upload mislukt',
    uploadErrorMsg: 'Fout bij het uploaden. Probeer het opnieuw.',
    rateExperience: 'Beoordeel Ervaring',
    good: 'Goed!',
    okay: 'Oké',
    notGreat: 'Niet geweldig',
    addPhotos: 'Foto\'s Toevoegen',
    selectImage: 'Kies afbeelding',
    genre: 'Genre',
    remove: 'Verwijderen',
    edit: 'Bewerken',
    inviteSelected: 'Nodig Geselecteerde Uit',
    sendingInvites: 'Verzenden...',
    selectFriendsLobby: 'Selecteer vrienden voor je lobby',
    noFriendsFound: 'Geen vrienden gevonden.',
    noAchievementsYet: 'Nog geen prestaties',



    // Explore Screen & Filters
    filters: "Filters",
    nameAZ: "Naam (A-Z)",
    any: "Alle",
    easy: "Makkelijk",
    medium: "Gemiddeld",
    hard: "Moeilijk",
    cityNamePlaceholder: "Stadsnaam...",
    minLabel: "Min",
    maxLabel: "Max",
    applyFilters: "Filters Toepassen",
    resetAllFilters: "Reset Filters",
    inProgressBadge: "Bezig",
    levelShort: "Niv",
    addFriendPlaceholder: "Vriend toevoegen via e-mail...",
    requests: "Verzoeken",
    wantsToBeFriend: "Wil vrienden worden",
    accept: "Accepteren",
    decline: "Weigeren",

    teamsFinishedCount: "teams klaar",
    of: "van",
    noOtherTeams: "Geen andere teams",
    otherTeams: "Andere Teams",
    walking: "Lopen",
    done: "Klaar",
    active: "Actief",
    setupTeamToStart: "Stel je team in om te starten!",
    everyoneIn: "Iedereen erbij? Laten we gaan!",
    setupTeamFirst: "Eerst Team Instellen",
    waitingForHost: "Wachten op host...",
    waitingForJoin: "Wachten op anderen...",
    host: "HOST",
    myTeam: "MIJN TEAM",

    // Profile Unique Keys
    reviewerLevel: "Recensent Niveau",
    topUp: "Opwaarderen",
    readyToJoin: "Klaar om mee te doen!",

    // Tour Detail & Feedback Unique Keys
    noReviewsYet: "Nog geen beoordelingen.",
    thanksFeedback: "Bedankt voor je feedback!",
    howWasExperience: "Hoe was je ervaring?",
    whatImprove: "Wat kunnen we verbeteren?",
    feedbackPlaceholder: "Vertel ons wat je niet leuk vond...",
    submitFeedback: "Feedback Versturen",

    // Genres
    nightlife: "Nachtleven",
    foodie: "Eten & Drinken",
    romance: "Romantiek",
    art: "Kunst & Muziek",
    photography: "Fotografie",
    noToursFound: "Geen tours gevonden",
  },
};
